# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/primer/visual/PrimerDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrimerDesign(object):
    def setupUi(self, PrimerDesign):
        PrimerDesign.setObjectName("PrimerDesign")
        PrimerDesign.resize(801, 608)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PrimerDesign)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(PrimerDesign)
        self.label.setStyleSheet("font: bold")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sequenceInputText = QtWidgets.QPlainTextEdit(PrimerDesign)
        self.sequenceInputText.setObjectName("sequenceInputText")
        self.verticalLayout.addWidget(self.sequenceInputText)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.primerDesignProgress = QtWidgets.QProgressBar(PrimerDesign)
        self.primerDesignProgress.setProperty("value", 24)
        self.primerDesignProgress.setObjectName("primerDesignProgress")
        self.horizontalLayout.addWidget(self.primerDesignProgress)
        self.label_3 = QtWidgets.QLabel(PrimerDesign)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.organismCombo = QtWidgets.QComboBox(PrimerDesign)
        self.organismCombo.setObjectName("organismCombo")
        self.horizontalLayout.addWidget(self.organismCombo)
        self.designPrimersButton = QtWidgets.QPushButton(PrimerDesign)
        self.designPrimersButton.setObjectName("designPrimersButton")
        self.horizontalLayout.addWidget(self.designPrimersButton)
        self.openPrimersButton = QtWidgets.QPushButton(PrimerDesign)
        self.openPrimersButton.setObjectName("openPrimersButton")
        self.horizontalLayout.addWidget(self.openPrimersButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(PrimerDesign)
        QtCore.QMetaObject.connectSlotsByName(PrimerDesign)

    def retranslateUi(self, PrimerDesign):
        _translate = QtCore.QCoreApplication.translate
        PrimerDesign.setWindowTitle(_translate("PrimerDesign", "PrimerDesigner"))
        self.label.setText(_translate("PrimerDesign", "Plasmid Sequence"))
        self.label_3.setText(_translate("PrimerDesign", "Organism"))
        self.designPrimersButton.setText(_translate("PrimerDesign", "Design Primers"))
        self.openPrimersButton.setText(_translate("PrimerDesign", "Open Primers"))
