# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/primer/visual/PrimerDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrimerDesign(object):
    def setupUi(self, PrimerDesign):
        PrimerDesign.setObjectName("PrimerDesign")
        PrimerDesign.resize(800, 600)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PrimerDesign)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(PrimerDesign)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sequenceInputText = QtWidgets.QPlainTextEdit(PrimerDesign)
        self.sequenceInputText.setObjectName("sequenceInputText")
        self.verticalLayout.addWidget(self.sequenceInputText)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(PrimerDesign)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.desiredTm = QtWidgets.QLineEdit(PrimerDesign)
        self.desiredTm.setMaximumSize(QtCore.QSize(50, 16777215))
        self.desiredTm.setObjectName("desiredTm")
        self.horizontalLayout.addWidget(self.desiredTm)
        self.designPrimersButton = QtWidgets.QPushButton(PrimerDesign)
        self.designPrimersButton.setObjectName("designPrimersButton")
        self.horizontalLayout.addWidget(self.designPrimersButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(PrimerDesign)
        QtCore.QMetaObject.connectSlotsByName(PrimerDesign)

    def retranslateUi(self, PrimerDesign):
        _translate = QtCore.QCoreApplication.translate
        PrimerDesign.setWindowTitle(_translate("PrimerDesign", "PrimerDesigner"))
        self.label.setText(_translate("PrimerDesign", "DNA Sequence"))
        self.label_2.setText(_translate("PrimerDesign", "Desired Tm"))
        self.designPrimersButton.setText(_translate("PrimerDesign", "Design Primers"))
