# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/primer/visual/PrimerResultViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrimerResultViewer(object):
    def setupUi(self, PrimerResultViewer):
        PrimerResultViewer.setObjectName("PrimerResultViewer")
        PrimerResultViewer.resize(392, 294)
        self.verticalLayout = QtWidgets.QVBoxLayout(PrimerResultViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resultTable = QtWidgets.QTableWidget(PrimerResultViewer)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setColumnCount(0)
        self.resultTable.setRowCount(0)
        self.verticalLayout.addWidget(self.resultTable)

        self.retranslateUi(PrimerResultViewer)
        QtCore.QMetaObject.connectSlotsByName(PrimerResultViewer)

    def retranslateUi(self, PrimerResultViewer):
        _translate = QtCore.QCoreApplication.translate
        PrimerResultViewer.setWindowTitle(_translate("PrimerResultViewer", "Form"))
