# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/primer/visual/PrimerDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrimerDesign(object):
    def setupUi(self, PrimerDesign):
        PrimerDesign.setObjectName("PrimerDesign")
        PrimerDesign.resize(801, 608)
        self.gridLayout = QtWidgets.QGridLayout(PrimerDesign)
        self.gridLayout.setObjectName("gridLayout")
        self.advancedButton = QtWidgets.QPushButton(PrimerDesign)
        self.advancedButton.setObjectName("advancedButton")
        self.gridLayout.addWidget(self.advancedButton, 5, 15, 1, 1)
        self.minSizeInput = QtWidgets.QLineEdit(PrimerDesign)
        self.minSizeInput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.minSizeInput.setObjectName("minSizeInput")
        self.gridLayout.addWidget(self.minSizeInput, 5, 12, 1, 1)
        self.openPrimersButton = QtWidgets.QPushButton(PrimerDesign)
        self.openPrimersButton.setObjectName("openPrimersButton")
        self.gridLayout.addWidget(self.openPrimersButton, 5, 17, 1, 1)
        self.label = QtWidgets.QLabel(PrimerDesign)
        self.label.setStyleSheet("font: bold")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 12)
        self.organismCombo = QtWidgets.QComboBox(PrimerDesign)
        self.organismCombo.setObjectName("organismCombo")
        self.gridLayout.addWidget(self.organismCombo, 5, 1, 1, 8)
        self.selectGeneTable = QtWidgets.QTableView(PrimerDesign)
        self.selectGeneTable.setObjectName("selectGeneTable")
        self.gridLayout.addWidget(self.selectGeneTable, 3, 0, 1, 18)
        self.maxSizeInput = QtWidgets.QLineEdit(PrimerDesign)
        self.maxSizeInput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.maxSizeInput.setObjectName("maxSizeInput")
        self.gridLayout.addWidget(self.maxSizeInput, 5, 14, 1, 1)
        self.sequenceInputText = QtWidgets.QPlainTextEdit(PrimerDesign)
        self.sequenceInputText.setObjectName("sequenceInputText")
        self.gridLayout.addWidget(self.sequenceInputText, 1, 0, 1, 18)
        self.label_5 = QtWidgets.QLabel(PrimerDesign)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 9, 1, 1)
        self.widget = QtWidgets.QWidget(PrimerDesign)
        self.widget.setMinimumSize(QtCore.QSize(0, 25))
        self.widget.setMaximumSize(QtCore.QSize(1, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(PrimerDesign)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 13, 1, 1)
        self.label_3 = QtWidgets.QLabel(PrimerDesign)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.concInput = QtWidgets.QLineEdit(PrimerDesign)
        self.concInput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.concInput.setObjectName("concInput")
        self.gridLayout.addWidget(self.concInput, 5, 10, 1, 1)
        self.designPrimersButton = QtWidgets.QPushButton(PrimerDesign)
        self.designPrimersButton.setObjectName("designPrimersButton")
        self.gridLayout.addWidget(self.designPrimersButton, 5, 16, 1, 1)
        self.label_2 = QtWidgets.QLabel(PrimerDesign)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 11, 1, 1)
        self.primerDesignProgress = QtWidgets.QProgressBar(PrimerDesign)
        self.primerDesignProgress.setMinimumSize(QtCore.QSize(0, 25))
        self.primerDesignProgress.setProperty("value", 24)
        self.primerDesignProgress.setObjectName("primerDesignProgress")
        self.gridLayout.addWidget(self.primerDesignProgress, 6, 1, 1, 17)
        self.label_6 = QtWidgets.QLabel(PrimerDesign)
        self.label_6.setStyleSheet("font-weight: bold;")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)

        self.retranslateUi(PrimerDesign)
        QtCore.QMetaObject.connectSlotsByName(PrimerDesign)

    def retranslateUi(self, PrimerDesign):
        _translate = QtCore.QCoreApplication.translate
        PrimerDesign.setWindowTitle(_translate("PrimerDesign", "PrimerDesigner"))
        self.advancedButton.setText(_translate("PrimerDesign", "Advanced Config"))
        self.openPrimersButton.setText(_translate("PrimerDesign", "Open Primers"))
        self.label.setText(_translate("PrimerDesign", "Plasmid Sequence"))
        self.label_5.setText(_translate("PrimerDesign", "Concentration (nM)"))
        self.label_4.setText(_translate("PrimerDesign", "Max Size"))
        self.label_3.setText(_translate("PrimerDesign", "Organism"))
        self.designPrimersButton.setText(_translate("PrimerDesign", "Design Primers"))
        self.label_2.setText(_translate("PrimerDesign", "Min Size"))
        self.label_6.setText(_translate("PrimerDesign", "Select Gene"))
