# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/core/Qt/visual/editrecords.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditRecords(object):
    def setupUi(self, EditRecords):
        EditRecords.setObjectName("EditRecords")
        EditRecords.resize(684, 516)
        self.gridLayout = QtWidgets.QGridLayout(EditRecords)
        self.gridLayout.setObjectName("gridLayout")
        self.saveButton = QtWidgets.QPushButton(EditRecords)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 1, 3, 1, 1)
        self.valuesTable = QtWidgets.QTableWidget(EditRecords)
        self.valuesTable.setObjectName("valuesTable")
        self.valuesTable.setColumnCount(0)
        self.valuesTable.setRowCount(0)
        self.gridLayout.addWidget(self.valuesTable, 0, 0, 1, 4)
        self.restoreDefaultsButton = QtWidgets.QPushButton(EditRecords)
        self.restoreDefaultsButton.setObjectName("restoreDefaultsButton")
        self.gridLayout.addWidget(self.restoreDefaultsButton, 1, 2, 1, 1)

        self.retranslateUi(EditRecords)
        QtCore.QMetaObject.connectSlotsByName(EditRecords)

    def retranslateUi(self, EditRecords):
        _translate = QtCore.QCoreApplication.translate
        EditRecords.setWindowTitle(_translate("EditRecords", "Dialog"))
        self.saveButton.setText(_translate("EditRecords", "Save"))
        self.restoreDefaultsButton.setText(_translate("EditRecords", "Restore Defaults"))
