# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/core/Qt/visual/NamedtupleEditorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NamedtupleEditorDialog(object):
    def setupUi(self, NamedtupleEditorDialog):
        NamedtupleEditorDialog.setObjectName("NamedtupleEditorDialog")
        NamedtupleEditorDialog.resize(442, 435)
        self.gridLayout = QtWidgets.QGridLayout(NamedtupleEditorDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.settingsTable = QtWidgets.QTableView(NamedtupleEditorDialog)
        self.settingsTable.setObjectName("settingsTable")
        self.gridLayout.addWidget(self.settingsTable, 0, 0, 1, 1)
        self.resultsButtons = QtWidgets.QDialogButtonBox(NamedtupleEditorDialog)
        self.resultsButtons.setOrientation(QtCore.Qt.Horizontal)
        self.resultsButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.resultsButtons.setObjectName("resultsButtons")
        self.gridLayout.addWidget(self.resultsButtons, 1, 0, 1, 1)

        self.retranslateUi(NamedtupleEditorDialog)
        self.resultsButtons.accepted.connect(NamedtupleEditorDialog.accept) # type: ignore
        self.resultsButtons.rejected.connect(NamedtupleEditorDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NamedtupleEditorDialog)

    def retranslateUi(self, NamedtupleEditorDialog):
        _translate = QtCore.QCoreApplication.translate
        NamedtupleEditorDialog.setWindowTitle(_translate("NamedtupleEditorDialog", "Dialog"))
