# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/kinetics/visual/KineticsInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KineticsInput(object):
    def setupUi(self, KineticsInput):
        KineticsInput.setObjectName("KineticsInput")
        KineticsInput.resize(919, 601)
        self.gridLayout = QtWidgets.QGridLayout(KineticsInput)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(KineticsInput)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(KineticsInput)
        self.label.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(KineticsInput)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.pasteDataButton = QtWidgets.QPushButton(KineticsInput)
        self.pasteDataButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pasteDataButton.setObjectName("pasteDataButton")
        self.gridLayout.addWidget(self.pasteDataButton, 3, 1, 1, 1)
        self.proceedButton = QtWidgets.QPushButton(KineticsInput)
        self.proceedButton.setObjectName("proceedButton")
        self.gridLayout.addWidget(self.proceedButton, 7, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(KineticsInput)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.runDataTable = QtWidgets.QTableWidget(KineticsInput)
        self.runDataTable.setObjectName("runDataTable")
        self.runDataTable.setColumnCount(0)
        self.runDataTable.setRowCount(0)
        self.gridLayout.addWidget(self.runDataTable, 4, 0, 1, 5)
        self.runGlobalsTable = QtWidgets.QTableView(KineticsInput)
        self.runGlobalsTable.setMinimumSize(QtCore.QSize(0, 0))
        self.runGlobalsTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.runGlobalsTable.setObjectName("runGlobalsTable")
        self.gridLayout.addWidget(self.runGlobalsTable, 2, 3, 1, 2)
        self.pasteParametersButton = QtWidgets.QPushButton(KineticsInput)
        self.pasteParametersButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pasteParametersButton.setObjectName("pasteParametersButton")
        self.gridLayout.addWidget(self.pasteParametersButton, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 3)
        self.runMetadataTable = QtWidgets.QTableView(KineticsInput)
        self.runMetadataTable.setObjectName("runMetadataTable")
        self.gridLayout.addWidget(self.runMetadataTable, 2, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 3)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setRowStretch(2, 3)
        self.gridLayout.setRowStretch(4, 6)

        self.retranslateUi(KineticsInput)
        QtCore.QMetaObject.connectSlotsByName(KineticsInput)

    def retranslateUi(self, KineticsInput):
        _translate = QtCore.QCoreApplication.translate
        KineticsInput.setWindowTitle(_translate("KineticsInput", "Form"))
        self.label_2.setText(_translate("KineticsInput", "Run Data"))
        self.label.setText(_translate("KineticsInput", "Kinetics"))
        self.label_4.setText(_translate("KineticsInput", "Run Globals"))
        self.pasteDataButton.setText(_translate("KineticsInput", "paste"))
        self.proceedButton.setText(_translate("KineticsInput", "Proceed"))
        self.label_3.setText(_translate("KineticsInput", "Run Parameters"))
        self.pasteParametersButton.setText(_translate("KineticsInput", "paste"))
