# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/kinetics/visual/KineticsOptimizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KineticsOptimizer(object):
    def setupUi(self, KineticsOptimizer):
        KineticsOptimizer.setObjectName("KineticsOptimizer")
        KineticsOptimizer.resize(489, 403)
        self.gridLayout = QtWidgets.QGridLayout(KineticsOptimizer)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(KineticsOptimizer)
        self.label.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.plotWidget = QtWidgets.QWidget(KineticsOptimizer)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout.addWidget(self.plotWidget, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(KineticsOptimizer)
        QtCore.QMetaObject.connectSlotsByName(KineticsOptimizer)

    def retranslateUi(self, KineticsOptimizer):
        _translate = QtCore.QCoreApplication.translate
        KineticsOptimizer.setWindowTitle(_translate("KineticsOptimizer", "Form"))
        self.label.setText(_translate("KineticsOptimizer", "Kinetics Optimizer"))
