# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/kinetics/visual/KineticsOptimizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KineticsOptimizer(object):
    def setupUi(self, KineticsOptimizer):
        KineticsOptimizer.setObjectName("KineticsOptimizer")
        KineticsOptimizer.resize(854, 611)
        self.gridLayout = QtWidgets.QGridLayout(KineticsOptimizer)
        self.gridLayout.setObjectName("gridLayout")
        self.plotWidget = QtWidgets.QWidget(KineticsOptimizer)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout.addWidget(self.plotWidget, 7, 0, 1, 1)
        self.betaWidget = QtWidgets.QWidget(KineticsOptimizer)
        self.betaWidget.setObjectName("betaWidget")
        self.gridLayout.addWidget(self.betaWidget, 5, 0, 1, 1)
        self.vmaxPlotWidget = QtWidgets.QWidget(KineticsOptimizer)
        self.vmaxPlotWidget.setObjectName("vmaxPlotWidget")
        self.gridLayout.addWidget(self.vmaxPlotWidget, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(KineticsOptimizer)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(KineticsOptimizer)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(KineticsOptimizer)
        self.label.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(KineticsOptimizer)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(5, 1)
        self.gridLayout.setRowStretch(7, 1)

        self.retranslateUi(KineticsOptimizer)
        QtCore.QMetaObject.connectSlotsByName(KineticsOptimizer)

    def retranslateUi(self, KineticsOptimizer):
        _translate = QtCore.QCoreApplication.translate
        KineticsOptimizer.setWindowTitle(_translate("KineticsOptimizer", "Form"))
        self.label_3.setText(_translate("KineticsOptimizer", "Beta and Ki"))
        self.label_2.setText(_translate("KineticsOptimizer", "Vmax and Km"))
        self.label.setText(_translate("KineticsOptimizer", "Kinetics Optimizer"))
        self.label_4.setText(_translate("KineticsOptimizer", "Result"))
