# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/kinetics/visual/LinearFitWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LinearFitWidget(object):
    def setupUi(self, LinearFitWidget):
        LinearFitWidget.setObjectName("LinearFitWidget")
        LinearFitWidget.resize(833, 482)
        self.gridLayout = QtWidgets.QGridLayout(LinearFitWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plotWidget = QtWidgets.QWidget(LinearFitWidget)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout.addWidget(self.plotWidget, 0, 0, 1, 1)
        self.statsTable = QtWidgets.QTableView(LinearFitWidget)
        self.statsTable.setObjectName("statsTable")
        self.gridLayout.addWidget(self.statsTable, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(LinearFitWidget)
        QtCore.QMetaObject.connectSlotsByName(LinearFitWidget)

    def retranslateUi(self, LinearFitWidget):
        _translate = QtCore.QCoreApplication.translate
        LinearFitWidget.setWindowTitle(_translate("LinearFitWidget", "Form"))
