# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/kinetics/visual/ParametersWizard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParametersWizard(object):
    def setupUi(self, ParametersWizard):
        ParametersWizard.setObjectName("ParametersWizard")
        ParametersWizard.resize(1031, 564)
        self.gridLayout = QtWidgets.QGridLayout(ParametersWizard)
        self.gridLayout.setObjectName("gridLayout")
        self.parametersTable = QtWidgets.QTableView(ParametersWizard)
        self.parametersTable.setObjectName("parametersTable")
        self.gridLayout.addWidget(self.parametersTable, 1, 0, 1, 1)
        self.initialValuesTab = QtWidgets.QTabWidget(ParametersWizard)
        self.initialValuesTab.setObjectName("initialValuesTab")
        self.gridLayout.addWidget(self.initialValuesTab, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(ParametersWizard)
        self.label.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.closeButtons = QtWidgets.QDialogButtonBox(ParametersWizard)
        self.closeButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.closeButtons.setObjectName("closeButtons")
        self.gridLayout.addWidget(self.closeButtons, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(ParametersWizard)
        QtCore.QMetaObject.connectSlotsByName(ParametersWizard)

    def retranslateUi(self, ParametersWizard):
        _translate = QtCore.QCoreApplication.translate
        ParametersWizard.setWindowTitle(_translate("ParametersWizard", "Dialog"))
        self.label.setText(_translate("ParametersWizard", "Model Parameters Wizard"))
