# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/kinetics/visual/PlotWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotWidget(object):
    def setupUi(self, PlotWidget):
        PlotWidget.setObjectName("PlotWidget")
        PlotWidget.resize(947, 660)
        self.horizontalLayout = QtWidgets.QHBoxLayout(PlotWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(PlotWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(6)
        self.splitter.setObjectName("splitter")
        self.plotContainer = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotContainer.sizePolicy().hasHeightForWidth())
        self.plotContainer.setSizePolicy(sizePolicy)
        self.plotContainer.setBaseSize(QtCore.QSize(0, 0))
        self.plotContainer.setObjectName("plotContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.plotContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plotWidget = QtWidgets.QWidget(self.plotContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setBaseSize(QtCore.QSize(0, 0))
        self.plotWidget.setObjectName("plotWidget")
        self.verticalLayout.addWidget(self.plotWidget)
        self.controlsContainer = QtWidgets.QWidget(self.splitter)
        self.controlsContainer.setObjectName("controlsContainer")
        self.gridLayout = QtWidgets.QGridLayout(self.controlsContainer)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.updateButton = QtWidgets.QPushButton(self.controlsContainer)
        self.updateButton.setObjectName("updateButton")
        self.gridLayout.addWidget(self.updateButton, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.selectedSeriesTable = QtWidgets.QTableView(self.controlsContainer)
        self.selectedSeriesTable.setObjectName("selectedSeriesTable")
        self.gridLayout.addWidget(self.selectedSeriesTable, 1, 0, 1, 2)
        self.dataTable = QtWidgets.QTableView(self.controlsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTable.sizePolicy().hasHeightForWidth())
        self.dataTable.setSizePolicy(sizePolicy)
        self.dataTable.setObjectName("dataTable")
        self.gridLayout.addWidget(self.dataTable, 0, 0, 1, 2)
        self.gridLayout.setRowStretch(0, 1)
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(PlotWidget)
        QtCore.QMetaObject.connectSlotsByName(PlotWidget)

    def retranslateUi(self, PlotWidget):
        _translate = QtCore.QCoreApplication.translate
        PlotWidget.setWindowTitle(_translate("PlotWidget", "Form"))
        self.updateButton.setText(_translate("PlotWidget", "Update"))
