# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/kinetics/visual/PlotWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotWidget(object):
    def setupUi(self, PlotWidget):
        PlotWidget.setObjectName("PlotWidget")
        PlotWidget.resize(947, 661)
        self.horizontalLayout = QtWidgets.QHBoxLayout(PlotWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(PlotWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(6)
        self.splitter.setObjectName("splitter")
        self.plotContainer = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotContainer.sizePolicy().hasHeightForWidth())
        self.plotContainer.setSizePolicy(sizePolicy)
        self.plotContainer.setBaseSize(QtCore.QSize(0, 0))
        self.plotContainer.setObjectName("plotContainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.plotContainer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plotWidget = QtWidgets.QWidget(self.plotContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.horizontalLayout_3.addWidget(self.plotWidget)
        self.controlsContainer = QtWidgets.QWidget(self.splitter)
        self.controlsContainer.setObjectName("controlsContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.controlsContainer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dataTable = QtWidgets.QTableView(self.controlsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTable.sizePolicy().hasHeightForWidth())
        self.dataTable.setSizePolicy(sizePolicy)
        self.dataTable.setObjectName("dataTable")
        self.horizontalLayout_2.addWidget(self.dataTable)
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(PlotWidget)
        QtCore.QMetaObject.connectSlotsByName(PlotWidget)

    def retranslateUi(self, PlotWidget):
        _translate = QtCore.QCoreApplication.translate
        PlotWidget.setWindowTitle(_translate("PlotWidget", "Form"))
