# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/kinetics/visual/VelocityFitWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VelocityFitWidget(object):
    def setupUi(self, VelocityFitWidget):
        VelocityFitWidget.setObjectName("VelocityFitWidget")
        VelocityFitWidget.resize(899, 655)
        self.gridLayout = QtWidgets.QGridLayout(VelocityFitWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.fitButton = QtWidgets.QPushButton(VelocityFitWidget)
        self.fitButton.setObjectName("fitButton")
        self.gridLayout.addWidget(self.fitButton, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.velocityPlot = QtWidgets.QWidget(VelocityFitWidget)
        self.velocityPlot.setObjectName("velocityPlot")
        self.gridLayout.addWidget(self.velocityPlot, 0, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.configurationWidget = QtWidgets.QTableView(VelocityFitWidget)
        self.configurationWidget.setObjectName("configurationWidget")
        self.gridLayout.addWidget(self.configurationWidget, 1, 1, 2, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setRowStretch(0, 1)

        self.retranslateUi(VelocityFitWidget)
        QtCore.QMetaObject.connectSlotsByName(VelocityFitWidget)

    def retranslateUi(self, VelocityFitWidget):
        _translate = QtCore.QCoreApplication.translate
        VelocityFitWidget.setWindowTitle(_translate("VelocityFitWidget", "Form"))
        self.fitButton.setText(_translate("VelocityFitWidget", "Fit"))
