# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/msa/visual/ColorByMotif.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ColorByMotif(object):
    def setupUi(self, ColorByMotif):
        ColorByMotif.setObjectName("ColorByMotif")
        ColorByMotif.resize(852, 627)
        self.gridLayout_3 = QtWidgets.QGridLayout(ColorByMotif)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.addKnownButton = QtWidgets.QPushButton(ColorByMotif)
        self.addKnownButton.setObjectName("addKnownButton")
        self.gridLayout_3.addWidget(self.addKnownButton, 0, 1, 1, 1)
        self.motifsTable = QtWidgets.QTableView(ColorByMotif)
        self.motifsTable.setObjectName("motifsTable")
        self.gridLayout_3.addWidget(self.motifsTable, 7, 0, 1, 2)
        self.knownCombo = QtWidgets.QComboBox(ColorByMotif)
        self.knownCombo.setObjectName("knownCombo")
        self.gridLayout_3.addWidget(self.knownCombo, 0, 0, 1, 1)
        self.removeSelected = QtWidgets.QPushButton(ColorByMotif)
        self.removeSelected.setObjectName("removeSelected")
        self.gridLayout_3.addWidget(self.removeSelected, 4, 0, 1, 1)
        self.runButton = QtWidgets.QPushButton(ColorByMotif)
        self.runButton.setObjectName("runButton")
        self.gridLayout_3.addWidget(self.runButton, 4, 1, 1, 1)
        self.viewsTabs = QtWidgets.QTabWidget(ColorByMotif)
        self.viewsTabs.setObjectName("viewsTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.structurePositionsTable = QtWidgets.QTableView(self.tab)
        self.structurePositionsTable.setObjectName("structurePositionsTable")
        self.gridLayout.addWidget(self.structurePositionsTable, 0, 0, 1, 2)
        self.viewsTabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.exportButton = QtWidgets.QPushButton(self.tab_2)
        self.exportButton.setObjectName("exportButton")
        self.gridLayout_2.addWidget(self.exportButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.msaItemsTable = QtWidgets.QTableView(self.tab_2)
        self.msaItemsTable.setObjectName("msaItemsTable")
        self.gridLayout_2.addWidget(self.msaItemsTable, 1, 0, 1, 2)
        self.viewsTabs.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.viewsTabs, 0, 3, 8, 5)
        self.customMotifName = QtWidgets.QLineEdit(ColorByMotif)
        self.customMotifName.setObjectName("customMotifName")
        self.gridLayout_3.addWidget(self.customMotifName, 3, 0, 1, 1)
        self.addCustomButton = QtWidgets.QPushButton(ColorByMotif)
        self.addCustomButton.setObjectName("addCustomButton")
        self.gridLayout_3.addWidget(self.addCustomButton, 3, 1, 1, 1)
        self.customLineEdit = QtWidgets.QLineEdit(ColorByMotif)
        self.customLineEdit.setObjectName("customLineEdit")
        self.gridLayout_3.addWidget(self.customLineEdit, 2, 0, 1, 2)
        self.gridLayout_3.setColumnStretch(7, 9)

        self.retranslateUi(ColorByMotif)
        self.viewsTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ColorByMotif)

    def retranslateUi(self, ColorByMotif):
        _translate = QtCore.QCoreApplication.translate
        ColorByMotif.setWindowTitle(_translate("ColorByMotif", "Form"))
        self.addKnownButton.setText(_translate("ColorByMotif", "Add Motif"))
        self.removeSelected.setText(_translate("ColorByMotif", "Remove Selected Motif"))
        self.runButton.setText(_translate("ColorByMotif", "Run"))
        self.viewsTabs.setTabText(self.viewsTabs.indexOf(self.tab), _translate("ColorByMotif", "View By Structure Position"))
        self.exportButton.setText(_translate("ColorByMotif", "Export"))
        self.viewsTabs.setTabText(self.viewsTabs.indexOf(self.tab_2), _translate("ColorByMotif", "View By Sequence Name"))
        self.customMotifName.setPlaceholderText(_translate("ColorByMotif", "Custom motif name"))
        self.addCustomButton.setText(_translate("ColorByMotif", "Add Custom Motif"))
        self.customLineEdit.setPlaceholderText(_translate("ColorByMotif", "Custom motif pattern"))
