# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/msa/visual/ColorByResidue.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ColorByResidue(object):
    def setupUi(self, ColorByResidue):
        ColorByResidue.setObjectName("ColorByResidue")
        ColorByResidue.resize(1056, 771)
        self.gridLayout = QtWidgets.QGridLayout(ColorByResidue)
        self.gridLayout.setObjectName("gridLayout")
        self.gapTresholdLabel = QtWidgets.QLabel(ColorByResidue)
        self.gapTresholdLabel.setObjectName("gapTresholdLabel")
        self.gridLayout.addWidget(self.gapTresholdLabel, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(ColorByResidue)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.scoringCombo = QtWidgets.QComboBox(ColorByResidue)
        self.scoringCombo.setMinimumSize(QtCore.QSize(200, 0))
        self.scoringCombo.setObjectName("scoringCombo")
        self.gridLayout.addWidget(self.scoringCombo, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(ColorByResidue)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gapTresholdSlider = QtWidgets.QSlider(ColorByResidue)
        self.gapTresholdSlider.setMaximum(100)
        self.gapTresholdSlider.setSliderPosition(100)
        self.gapTresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gapTresholdSlider.setObjectName("gapTresholdSlider")
        self.gridLayout.addWidget(self.gapTresholdSlider, 0, 1, 1, 1)
        self.colorConservedButton = QtWidgets.QPushButton(ColorByResidue)
        self.colorConservedButton.setObjectName("colorConservedButton")
        self.gridLayout.addWidget(self.colorConservedButton, 0, 5, 1, 1)
        self.resultsTable = QtWidgets.QTableWidget(ColorByResidue)
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(0)
        self.resultsTable.setRowCount(0)
        self.gridLayout.addWidget(self.resultsTable, 1, 0, 1, 6)

        self.retranslateUi(ColorByResidue)
        QtCore.QMetaObject.connectSlotsByName(ColorByResidue)

    def retranslateUi(self, ColorByResidue):
        _translate = QtCore.QCoreApplication.translate
        ColorByResidue.setWindowTitle(_translate("ColorByResidue", "Form"))
        self.gapTresholdLabel.setText(_translate("ColorByResidue", "100%"))
        self.label_3.setText(_translate("ColorByResidue", "Scoring"))
        self.label.setText(_translate("ColorByResidue", "Color Gaps Treshold"))
        self.colorConservedButton.setText(_translate("ColorByResidue", "Color Conserved Regions"))
