# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/msa/visual/FastaViewerApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FastaViewerApp(object):
    def setupUi(self, FastaViewerApp):
        FastaViewerApp.setObjectName("FastaViewerApp")
        FastaViewerApp.resize(536, 485)
        self.gridLayout = QtWidgets.QGridLayout(FastaViewerApp)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(FastaViewerApp)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.browseButton = QtWidgets.QPushButton(FastaViewerApp)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 1, 1, 1, 2)
        self.selectedFileLabel = QtWidgets.QLabel(FastaViewerApp)
        self.selectedFileLabel.setText("")
        self.selectedFileLabel.setObjectName("selectedFileLabel")
        self.gridLayout.addWidget(self.selectedFileLabel, 1, 3, 1, 1)
        self.fastaViewerWidget = FastaViewer(FastaViewerApp)
        self.fastaViewerWidget.setObjectName("fastaViewerWidget")
        self.gridLayout.addWidget(self.fastaViewerWidget, 2, 0, 1, 4)
        self.label = QtWidgets.QLabel(FastaViewerApp)
        self.label.setStyleSheet("font-size: 26px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setRowStretch(2, 1)

        self.retranslateUi(FastaViewerApp)
        QtCore.QMetaObject.connectSlotsByName(FastaViewerApp)

    def retranslateUi(self, FastaViewerApp):
        _translate = QtCore.QCoreApplication.translate
        FastaViewerApp.setWindowTitle(_translate("FastaViewerApp", "Form"))
        self.label_2.setText(_translate("FastaViewerApp", "Select Fasta"))
        self.browseButton.setText(_translate("FastaViewerApp", "Browse"))
        self.label.setText(_translate("FastaViewerApp", "Fasta Viewer"))
from ...support.fasta.visual.FastaViewer import FastaViewer
