# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/msa/visual/MsaViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MsaViewer(object):
    def setupUi(self, MsaViewer):
        MsaViewer.setObjectName("MsaViewer")
        MsaViewer.resize(1084, 847)
        self.gridLayout = QtWidgets.QGridLayout(MsaViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.createMsaButton = QtWidgets.QPushButton(MsaViewer)
        self.createMsaButton.setObjectName("createMsaButton")
        self.gridLayout.addWidget(self.createMsaButton, 0, 5, 1, 1)
        self.structuresCombo = QtWidgets.QComboBox(MsaViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.structuresCombo.sizePolicy().hasHeightForWidth())
        self.structuresCombo.setSizePolicy(sizePolicy)
        self.structuresCombo.setMinimumSize(QtCore.QSize(200, 0))
        self.structuresCombo.setObjectName("structuresCombo")
        self.gridLayout.addWidget(self.structuresCombo, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(MsaViewer)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(MsaViewer)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.selectedFileLabel = QtWidgets.QLabel(MsaViewer)
        self.selectedFileLabel.setText("")
        self.selectedFileLabel.setObjectName("selectedFileLabel")
        self.gridLayout.addWidget(self.selectedFileLabel, 1, 4, 1, 4)
        self.msaColoringWidgets = QtWidgets.QTabWidget(MsaViewer)
        self.msaColoringWidgets.setObjectName("msaColoringWidgets")
        self.gridLayout.addWidget(self.msaColoringWidgets, 2, 0, 1, 8)
        self.structuresRefreshButton = QtWidgets.QPushButton(MsaViewer)
        self.structuresRefreshButton.setObjectName("structuresRefreshButton")
        self.gridLayout.addWidget(self.structuresRefreshButton, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(MsaViewer)
        self.label_3.setMinimumSize(QtCore.QSize(136, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 2)
        self.selectMsaButton = QtWidgets.QPushButton(MsaViewer)
        self.selectMsaButton.setMinimumSize(QtCore.QSize(0, 0))
        self.selectMsaButton.setObjectName("selectMsaButton")
        self.gridLayout.addWidget(self.selectMsaButton, 0, 4, 1, 1)
        self.sequenceCombo = QtWidgets.QComboBox(MsaViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequenceCombo.sizePolicy().hasHeightForWidth())
        self.sequenceCombo.setSizePolicy(sizePolicy)
        self.sequenceCombo.setMinimumSize(QtCore.QSize(200, 0))
        self.sequenceCombo.setObjectName("sequenceCombo")
        self.gridLayout.addWidget(self.sequenceCombo, 1, 1, 1, 1)

        self.retranslateUi(MsaViewer)
        QtCore.QMetaObject.connectSlotsByName(MsaViewer)

    def retranslateUi(self, MsaViewer):
        _translate = QtCore.QCoreApplication.translate
        MsaViewer.setWindowTitle(_translate("MsaViewer", "Form"))
        self.createMsaButton.setText(_translate("MsaViewer", "Create"))
        self.label.setText(_translate("MsaViewer", "MSA File"))
        self.label_2.setText(_translate("MsaViewer", "Structure"))
        self.structuresRefreshButton.setText(_translate("MsaViewer", "Refresh"))
        self.label_3.setText(_translate("MsaViewer", "MSA Structure Sequence"))
        self.selectMsaButton.setText(_translate("MsaViewer", "Browse"))
