# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/msa/visual/MsaCleaner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MsaCleaner(object):
    def setupUi(self, MsaCleaner):
        MsaCleaner.setObjectName("MsaCleaner")
        MsaCleaner.resize(858, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(MsaCleaner)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(MsaCleaner)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scoresTable = QtWidgets.QTableView(self.widget)
        self.scoresTable.setObjectName("scoresTable")
        self.gridLayout.addWidget(self.scoresTable, 1, 0, 1, 1)
        self.msaViewerContainerWidget = QtWidgets.QWidget(self.widget)
        self.msaViewerContainerWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.msaViewerContainerWidget.setObjectName("msaViewerContainerWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.msaViewerContainerWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.msaViewerWidget = QtWidgets.QWidget(self.msaViewerContainerWidget)
        self.msaViewerWidget.setObjectName("msaViewerWidget")
        self.horizontalLayout.addWidget(self.msaViewerWidget)
        self.gridLayout.addWidget(self.msaViewerContainerWidget, 2, 0, 1, 2)
        self.statsTable = QtWidgets.QTableView(self.widget)
        self.statsTable.setObjectName("statsTable")
        self.gridLayout.addWidget(self.statsTable, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font-size: 28px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 9)
        self.gridLayout.setRowStretch(2, 9)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selectedFileLabel = QtWidgets.QLabel(self.widget1)
        self.selectedFileLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.selectedFileLabel.setText("")
        self.selectedFileLabel.setObjectName("selectedFileLabel")
        self.gridLayout_2.addWidget(self.selectedFileLabel, 1, 1, 1, 2)
        self.pruneButton = QtWidgets.QPushButton(self.widget1)
        self.pruneButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pruneButton.setObjectName("pruneButton")
        self.gridLayout_2.addWidget(self.pruneButton, 3, 1, 1, 1)
        self.loadMsaButton = QtWidgets.QPushButton(self.widget1)
        self.loadMsaButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.loadMsaButton.setObjectName("loadMsaButton")
        self.gridLayout_2.addWidget(self.loadMsaButton, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.cleanersWidget = QtWidgets.QTabWidget(self.widget1)
        self.cleanersWidget.setObjectName("cleanersWidget")
        self.gridLayout_2.addWidget(self.cleanersWidget, 0, 0, 4, 1)
        self.saveResultsButtons = QtWidgets.QPushButton(self.widget1)
        self.saveResultsButtons.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.saveResultsButtons.setObjectName("saveResultsButtons")
        self.gridLayout_2.addWidget(self.saveResultsButtons, 3, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 6)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(MsaCleaner)
        QtCore.QMetaObject.connectSlotsByName(MsaCleaner)

    def retranslateUi(self, MsaCleaner):
        _translate = QtCore.QCoreApplication.translate
        MsaCleaner.setWindowTitle(_translate("MsaCleaner", "Form"))
        self.label.setText(_translate("MsaCleaner", "MSA Cleaner"))
        self.pruneButton.setText(_translate("MsaCleaner", "Prune"))
        self.loadMsaButton.setText(_translate("MsaCleaner", "Load MSA"))
        self.saveResultsButtons.setText(_translate("MsaCleaner", "Save Results"))
