# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/msa/visual/MsaCleaner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MsaCleaner(object):
    def setupUi(self, MsaCleaner):
        MsaCleaner.setObjectName("MsaCleaner")
        MsaCleaner.resize(912, 546)
        self.gridLayout = QtWidgets.QGridLayout(MsaCleaner)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(MsaCleaner)
        self.label.setStyleSheet("font-size: 28px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.scoresTable = QtWidgets.QTableView(MsaCleaner)
        self.scoresTable.setObjectName("scoresTable")
        self.gridLayout.addWidget(self.scoresTable, 1, 0, 1, 1)
        self.statsTable = QtWidgets.QTableView(MsaCleaner)
        self.statsTable.setObjectName("statsTable")
        self.gridLayout.addWidget(self.statsTable, 1, 1, 1, 1)
        self.msaViewerWidget = QtWidgets.QWidget(MsaCleaner)
        self.msaViewerWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.msaViewerWidget.setObjectName("msaViewerWidget")
        self.gridLayout.addWidget(self.msaViewerWidget, 2, 0, 1, 2)
        self.selectedFileLabel = QtWidgets.QLabel(MsaCleaner)
        self.selectedFileLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.selectedFileLabel.setText("")
        self.selectedFileLabel.setObjectName("selectedFileLabel")
        self.gridLayout.addWidget(self.selectedFileLabel, 3, 1, 1, 1)
        self.loadMsaButton = QtWidgets.QPushButton(MsaCleaner)
        self.loadMsaButton.setObjectName("loadMsaButton")
        self.gridLayout.addWidget(self.loadMsaButton, 4, 1, 1, 1)
        self.saveResultsButtons = QtWidgets.QPushButton(MsaCleaner)
        self.saveResultsButtons.setObjectName("saveResultsButtons")
        self.gridLayout.addWidget(self.saveResultsButtons, 5, 1, 1, 1)
        self.cleanersWidget = QtWidgets.QTabWidget(MsaCleaner)
        self.cleanersWidget.setObjectName("cleanersWidget")
        self.gridLayout.addWidget(self.cleanersWidget, 3, 0, 3, 1)
        self.gridLayout.setColumnStretch(0, 9)
        self.gridLayout.setRowStretch(1, 9)
        self.gridLayout.setRowStretch(2, 9)

        self.retranslateUi(MsaCleaner)
        QtCore.QMetaObject.connectSlotsByName(MsaCleaner)

    def retranslateUi(self, MsaCleaner):
        _translate = QtCore.QCoreApplication.translate
        MsaCleaner.setWindowTitle(_translate("MsaCleaner", "Form"))
        self.label.setText(_translate("MsaCleaner", "MSA Cleaner"))
        self.loadMsaButton.setText(_translate("MsaCleaner", "Load MSA"))
        self.saveResultsButtons.setText(_translate("MsaCleaner", "Save Results"))
