# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/msa/visual/MsaCleaner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MsaCleaner(object):
    def setupUi(self, MsaCleaner):
        MsaCleaner.setObjectName("MsaCleaner")
        MsaCleaner.resize(849, 637)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MsaCleaner)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(MsaCleaner)
        self.label.setStyleSheet("font-size: 28px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.splitter = QtWidgets.QSplitter(MsaCleaner)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.msaViewerAndScoreLayout = QtWidgets.QVBoxLayout(self.widget)
        self.msaViewerAndScoreLayout.setContentsMargins(0, 0, 0, 0)
        self.msaViewerAndScoreLayout.setObjectName("msaViewerAndScoreLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scoresTable = QtWidgets.QTableView(self.widget)
        self.scoresTable.setObjectName("scoresTable")
        self.horizontalLayout.addWidget(self.scoresTable)
        self.statsTable = QtWidgets.QTableView(self.widget)
        self.statsTable.setObjectName("statsTable")
        self.horizontalLayout.addWidget(self.statsTable)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 2)
        self.msaViewerAndScoreLayout.addLayout(self.horizontalLayout)
        self.msaViewerWidget = QtWidgets.QWidget(self.widget)
        self.msaViewerWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.msaViewerWidget.setObjectName("msaViewerWidget")
        self.msaViewerAndScoreLayout.addWidget(self.msaViewerWidget)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cleanersWidget = QtWidgets.QTabWidget(self.widget1)
        self.cleanersWidget.setObjectName("cleanersWidget")
        self.horizontalLayout_2.addWidget(self.cleanersWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.selectedFileLabel = QtWidgets.QLabel(self.widget1)
        self.selectedFileLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.selectedFileLabel.setText("")
        self.selectedFileLabel.setObjectName("selectedFileLabel")
        self.verticalLayout.addWidget(self.selectedFileLabel)
        self.loadMsaButton = QtWidgets.QPushButton(self.widget1)
        self.loadMsaButton.setObjectName("loadMsaButton")
        self.verticalLayout.addWidget(self.loadMsaButton)
        self.saveResultsButtons = QtWidgets.QPushButton(self.widget1)
        self.saveResultsButtons.setObjectName("saveResultsButtons")
        self.verticalLayout.addWidget(self.saveResultsButtons)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(MsaCleaner)
        QtCore.QMetaObject.connectSlotsByName(MsaCleaner)

    def retranslateUi(self, MsaCleaner):
        _translate = QtCore.QCoreApplication.translate
        MsaCleaner.setWindowTitle(_translate("MsaCleaner", "Form"))
        self.label.setText(_translate("MsaCleaner", "MSA Cleaner"))
        self.loadMsaButton.setText(_translate("MsaCleaner", "Load MSA"))
        self.saveResultsButtons.setText(_translate("MsaCleaner", "Save Results"))
