# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/msa/visual/ScoreByDivergence.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScoreByDivergence(object):
    def setupUi(self, ScoreByDivergence):
        ScoreByDivergence.setObjectName("ScoreByDivergence")
        ScoreByDivergence.resize(504, 203)
        self.verticalLayout = QtWidgets.QVBoxLayout(ScoreByDivergence)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ScoreByDivergence)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.divergenceSlider = QtWidgets.QSlider(ScoreByDivergence)
        self.divergenceSlider.setMaximum(100)
        self.divergenceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.divergenceSlider.setObjectName("divergenceSlider")
        self.horizontalLayout.addWidget(self.divergenceSlider)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 159, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(ScoreByDivergence)
        QtCore.QMetaObject.connectSlotsByName(ScoreByDivergence)

    def retranslateUi(self, ScoreByDivergence):
        _translate = QtCore.QCoreApplication.translate
        ScoreByDivergence.setWindowTitle(_translate("ScoreByDivergence", "Form"))
        self.label.setText(_translate("ScoreByDivergence", "Gap Divergence Treshold"))
