# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/msa/visual/ScoreByLongInserts.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScoreByLongInserts(object):
    def setupUi(self, ScoreByLongInserts):
        ScoreByLongInserts.setObjectName("ScoreByLongInserts")
        ScoreByLongInserts.resize(555, 243)
        self.gridLayout = QtWidgets.QGridLayout(ScoreByLongInserts)
        self.gridLayout.setObjectName("gridLayout")
        self.continuityTresholdSlider = QtWidgets.QSlider(ScoreByLongInserts)
        self.continuityTresholdSlider.setProperty("value", 90)
        self.continuityTresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.continuityTresholdSlider.setObjectName("continuityTresholdSlider")
        self.gridLayout.addWidget(self.continuityTresholdSlider, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 2)
        self.descriptionLabel = QtWidgets.QLabel(ScoreByLongInserts)
        self.descriptionLabel.setText("")
        self.descriptionLabel.setWordWrap(True)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.gridLayout.addWidget(self.descriptionLabel, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(ScoreByLongInserts)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        self.retranslateUi(ScoreByLongInserts)
        QtCore.QMetaObject.connectSlotsByName(ScoreByLongInserts)

    def retranslateUi(self, ScoreByLongInserts):
        _translate = QtCore.QCoreApplication.translate
        ScoreByLongInserts.setWindowTitle(_translate("ScoreByLongInserts", "Form"))
        self.label.setText(_translate("ScoreByLongInserts", "Continuity Treshold"))
