# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/msa/visual/ScoreByLength.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScoreByLength(object):
    def setupUi(self, ScoreByLength):
        ScoreByLength.setObjectName("ScoreByLength")
        ScoreByLength.resize(468, 172)
        self.gridLayout = QtWidgets.QGridLayout(ScoreByLength)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(ScoreByLength)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ScoreByLength)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.maxSlider = QtWidgets.QSlider(ScoreByLength)
        self.maxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider.setObjectName("maxSlider")
        self.gridLayout.addWidget(self.maxSlider, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.minSlider = QtWidgets.QSlider(ScoreByLength)
        self.minSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minSlider.setObjectName("minSlider")
        self.gridLayout.addWidget(self.minSlider, 1, 1, 1, 1)
        self.descriptionLabel = QtWidgets.QLabel(ScoreByLength)
        self.descriptionLabel.setText("")
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.gridLayout.addWidget(self.descriptionLabel, 0, 0, 1, 2)
        self.minLengthLabel = QtWidgets.QLabel(ScoreByLength)
        self.minLengthLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.minLengthLabel.setText("")
        self.minLengthLabel.setObjectName("minLengthLabel")
        self.gridLayout.addWidget(self.minLengthLabel, 1, 2, 1, 1)
        self.maxLenghtLabel = QtWidgets.QLabel(ScoreByLength)
        self.maxLenghtLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.maxLenghtLabel.setText("")
        self.maxLenghtLabel.setObjectName("maxLenghtLabel")
        self.gridLayout.addWidget(self.maxLenghtLabel, 2, 2, 1, 1)

        self.retranslateUi(ScoreByLength)
        QtCore.QMetaObject.connectSlotsByName(ScoreByLength)

    def retranslateUi(self, ScoreByLength):
        _translate = QtCore.QCoreApplication.translate
        ScoreByLength.setWindowTitle(_translate("ScoreByLength", "Form"))
        self.label_3.setText(_translate("ScoreByLength", "Maximum Length"))
        self.label_2.setText(_translate("ScoreByLength", "Minimum Length"))
