# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/msa/visual/ScoreWithScope.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScoreWithScope(object):
    def setupUi(self, ScoreWithScope):
        ScoreWithScope.setObjectName("ScoreWithScope")
        ScoreWithScope.resize(617, 354)
        self.gridLayout = QtWidgets.QGridLayout(ScoreWithScope)
        self.gridLayout.setObjectName("gridLayout")
        self.tresholdSlider = QtWidgets.QSlider(ScoreWithScope)
        self.tresholdSlider.setMaximum(100)
        self.tresholdSlider.setProperty("value", 100)
        self.tresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tresholdSlider.setObjectName("tresholdSlider")
        self.gridLayout.addWidget(self.tresholdSlider, 1, 1, 1, 1)
        self.scopeStartSlider = QtWidgets.QSlider(ScoreWithScope)
        self.scopeStartSlider.setMinimum(1)
        self.scopeStartSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scopeStartSlider.setObjectName("scopeStartSlider")
        self.gridLayout.addWidget(self.scopeStartSlider, 2, 1, 1, 1)
        self.scopeEndSlider = QtWidgets.QSlider(ScoreWithScope)
        self.scopeEndSlider.setMinimum(1)
        self.scopeEndSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scopeEndSlider.setObjectName("scopeEndSlider")
        self.gridLayout.addWidget(self.scopeEndSlider, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(ScoreWithScope)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(ScoreWithScope)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ScoreWithScope)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.tresholdLabel = QtWidgets.QLabel(ScoreWithScope)
        self.tresholdLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.tresholdLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tresholdLabel.setText("")
        self.tresholdLabel.setObjectName("tresholdLabel")
        self.gridLayout.addWidget(self.tresholdLabel, 1, 2, 1, 1)
        self.scopeStartLabel = QtWidgets.QLabel(ScoreWithScope)
        self.scopeStartLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.scopeStartLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.scopeStartLabel.setText("")
        self.scopeStartLabel.setObjectName("scopeStartLabel")
        self.gridLayout.addWidget(self.scopeStartLabel, 2, 2, 1, 1)
        self.scopeEndLabel = QtWidgets.QLabel(ScoreWithScope)
        self.scopeEndLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.scopeEndLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.scopeEndLabel.setText("")
        self.scopeEndLabel.setObjectName("scopeEndLabel")
        self.gridLayout.addWidget(self.scopeEndLabel, 3, 2, 1, 1)
        self.scoreWidget = QtWidgets.QWidget(ScoreWithScope)
        self.scoreWidget.setObjectName("scoreWidget")
        self.gridLayout.addWidget(self.scoreWidget, 0, 0, 1, 3)

        self.retranslateUi(ScoreWithScope)
        QtCore.QMetaObject.connectSlotsByName(ScoreWithScope)

    def retranslateUi(self, ScoreWithScope):
        _translate = QtCore.QCoreApplication.translate
        ScoreWithScope.setWindowTitle(_translate("ScoreWithScope", "Form"))
        self.label.setText(_translate("ScoreWithScope", "Treshold"))
        self.label_3.setText(_translate("ScoreWithScope", "Scope End"))
        self.label_2.setText(_translate("ScoreWithScope", "Scope Start"))
