# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/frankenprot/visual/FrankenProt.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrankenProt(object):
    def setupUi(self, FrankenProt):
        FrankenProt.setObjectName("FrankenProt")
        FrankenProt.resize(741, 497)
        self.gridLayout = QtWidgets.QGridLayout(FrankenProt)
        self.gridLayout.setObjectName("gridLayout")
        self.sequencesTable = QtWidgets.QTableView(FrankenProt)
        self.sequencesTable.setObjectName("sequencesTable")
        self.gridLayout.addWidget(self.sequencesTable, 2, 0, 1, 7)
        self.label_3 = QtWidgets.QLabel(FrankenProt)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.statusProgress = QtWidgets.QProgressBar(FrankenProt)
        self.statusProgress.setMaximum(0)
        self.statusProgress.setProperty("value", -1)
        self.statusProgress.setObjectName("statusProgress")
        self.gridLayout.addWidget(self.statusProgress, 3, 0, 1, 7)
        self.baseStructureCombo = QtWidgets.QComboBox(FrankenProt)
        self.baseStructureCombo.setObjectName("baseStructureCombo")
        self.gridLayout.addWidget(self.baseStructureCombo, 1, 1, 1, 1)
        self.fragmentsStructureCombo = QtWidgets.QComboBox(FrankenProt)
        self.fragmentsStructureCombo.setObjectName("fragmentsStructureCombo")
        self.gridLayout.addWidget(self.fragmentsStructureCombo, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(192, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 6, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(FrankenProt)
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout.addWidget(self.refreshButton, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(FrankenProt)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(FrankenProt)
        self.label.setStyleSheet("font-size: 26px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.selectButton = QtWidgets.QPushButton(FrankenProt)
        self.selectButton.setObjectName("selectButton")
        self.gridLayout.addWidget(self.selectButton, 1, 5, 1, 1)

        self.retranslateUi(FrankenProt)
        QtCore.QMetaObject.connectSlotsByName(FrankenProt)

    def retranslateUi(self, FrankenProt):
        _translate = QtCore.QCoreApplication.translate
        FrankenProt.setWindowTitle(_translate("FrankenProt", "Form"))
        self.label_3.setText(_translate("FrankenProt", "Fragments Structure"))
        self.refreshButton.setText(_translate("FrankenProt", "Refresh"))
        self.label_2.setText(_translate("FrankenProt", "Base Structure"))
        self.label.setText(_translate("FrankenProt", "FrankenProt"))
        self.selectButton.setText(_translate("FrankenProt", "Select"))
