# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/sequences/visual/CreateDatabaseDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateDatabaseDialog(object):
    def setupUi(self, CreateDatabaseDialog):
        CreateDatabaseDialog.setObjectName("CreateDatabaseDialog")
        CreateDatabaseDialog.resize(909, 580)
        self.gridLayout = QtWidgets.QGridLayout(CreateDatabaseDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(CreateDatabaseDialog)
        self.label_5.setStyleSheet("font-weight: bold;")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(CreateDatabaseDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.createButton = QtWidgets.QPushButton(CreateDatabaseDialog)
        self.createButton.setObjectName("createButton")
        self.gridLayout.addWidget(self.createButton, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(CreateDatabaseDialog)
        self.label.setStyleSheet("font-size: 26px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.selectedFileLabel = QtWidgets.QLabel(CreateDatabaseDialog)
        self.selectedFileLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.selectedFileLabel.setText("")
        self.selectedFileLabel.setObjectName("selectedFileLabel")
        self.gridLayout.addWidget(self.selectedFileLabel, 3, 2, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(CreateDatabaseDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 6, 4, 1, 1)
        self.browseButton = QtWidgets.QPushButton(CreateDatabaseDialog)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 3, 1, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(CreateDatabaseDialog)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(CreateDatabaseDialog)
        self.label_4.setStyleSheet("font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(CreateDatabaseDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 3, 1, 1)
        self.databasesTable = QtWidgets.QTableView(CreateDatabaseDialog)
        self.databasesTable.setObjectName("databasesTable")
        self.gridLayout.addWidget(self.databasesTable, 2, 3, 4, 2)
        self.gridLayout.setColumnStretch(3, 1)

        self.retranslateUi(CreateDatabaseDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateDatabaseDialog)

    def retranslateUi(self, CreateDatabaseDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateDatabaseDialog.setWindowTitle(_translate("CreateDatabaseDialog", "Dialog"))
        self.label_5.setText(_translate("CreateDatabaseDialog", "Option 2: Open Existing"))
        self.label_2.setText(_translate("CreateDatabaseDialog", "Name"))
        self.createButton.setText(_translate("CreateDatabaseDialog", "Create"))
        self.label.setText(_translate("CreateDatabaseDialog", "Open or Create a DNA Database"))
        self.cancelButton.setText(_translate("CreateDatabaseDialog", "Cancel"))
        self.browseButton.setText(_translate("CreateDatabaseDialog", "Browse"))
        self.nameLineEdit.setText(_translate("CreateDatabaseDialog", "New Database"))
        self.label_4.setText(_translate("CreateDatabaseDialog", "Option 1: Create New Database"))
        self.label_3.setText(_translate("CreateDatabaseDialog", "Search Folder"))
