# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/sequences/visual/SearchOrganismsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchOrganismsWidget(object):
    def setupUi(self, SearchOrganismsWidget):
        SearchOrganismsWidget.setObjectName("SearchOrganismsWidget")
        SearchOrganismsWidget.resize(1298, 698)
        SearchOrganismsWidget.setStyleSheet(".QComboBox {\n"
"    min-width: 100px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(SearchOrganismsWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.busy_progress = QtWidgets.QProgressBar(SearchOrganismsWidget)
        self.busy_progress.setProperty("value", 24)
        self.busy_progress.setObjectName("busy_progress")
        self.gridLayout.addWidget(self.busy_progress, 3, 5, 1, 4)
        self.label_3 = QtWidgets.QLabel(SearchOrganismsWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.name_combo = QtWidgets.QComboBox(SearchOrganismsWidget)
        self.name_combo.setObjectName("name_combo")
        self.gridLayout.addWidget(self.name_combo, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(SearchOrganismsWidget)
        self.label.setStyleSheet("font-size: 26px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 5, 1, 1)
        self.add_to_database_button = QtWidgets.QPushButton(SearchOrganismsWidget)
        self.add_to_database_button.setObjectName("add_to_database_button")
        self.gridLayout.addWidget(self.add_to_database_button, 2, 6, 1, 3)
        self.search_button = QtWidgets.QPushButton(SearchOrganismsWidget)
        self.search_button.setObjectName("search_button")
        self.gridLayout.addWidget(self.search_button, 3, 3, 1, 2)
        self.taxid_combo = QtWidgets.QComboBox(SearchOrganismsWidget)
        self.taxid_combo.setObjectName("taxid_combo")
        self.gridLayout.addWidget(self.taxid_combo, 3, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(SearchOrganismsWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 1)
        self.accession_combo = QtWidgets.QComboBox(SearchOrganismsWidget)
        self.accession_combo.setObjectName("accession_combo")
        self.gridLayout.addWidget(self.accession_combo, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(SearchOrganismsWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(SearchOrganismsWidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.search_table = QtWidgets.QTableWidget(self.splitter)
        self.search_table.setObjectName("search_table")
        self.search_table.setColumnCount(0)
        self.search_table.setRowCount(0)
        self.results_table = QtWidgets.QTableView(self.splitter)
        self.results_table.setObjectName("results_table")
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 9)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(SearchOrganismsWidget)
        QtCore.QMetaObject.connectSlotsByName(SearchOrganismsWidget)

    def retranslateUi(self, SearchOrganismsWidget):
        _translate = QtCore.QCoreApplication.translate
        SearchOrganismsWidget.setWindowTitle(_translate("SearchOrganismsWidget", "Form"))
        self.label_3.setText(_translate("SearchOrganismsWidget", "TaxID Column"))
        self.label.setText(_translate("SearchOrganismsWidget", "Search Organisms"))
        self.add_to_database_button.setText(_translate("SearchOrganismsWidget", "Add Selected to Database"))
        self.search_button.setText(_translate("SearchOrganismsWidget", "Search"))
        self.label_4.setText(_translate("SearchOrganismsWidget", "Accession Column"))
        self.label_2.setText(_translate("SearchOrganismsWidget", "Name Column"))
