# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/support/msa/visual/FastaSequencesInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FastaSequencesInput(object):
    def setupUi(self, FastaSequencesInput):
        FastaSequencesInput.setObjectName("FastaSequencesInput")
        FastaSequencesInput.resize(417, 314)
        self.verticalLayout = QtWidgets.QVBoxLayout(FastaSequencesInput)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(FastaSequencesInput)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sequenceTextEdit = QtWidgets.QPlainTextEdit(FastaSequencesInput)
        self.sequenceTextEdit.setObjectName("sequenceTextEdit")
        self.verticalLayout.addWidget(self.sequenceTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.errorLabel = QtWidgets.QLabel(FastaSequencesInput)
        font = QtGui.QFont()
        font.setBold(True)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("color: red;")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.horizontalLayout.addWidget(self.errorLabel)
        self.sequenceButtonBox = QtWidgets.QDialogButtonBox(FastaSequencesInput)
        self.sequenceButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.sequenceButtonBox.setObjectName("sequenceButtonBox")
        self.horizontalLayout.addWidget(self.sequenceButtonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FastaSequencesInput)
        QtCore.QMetaObject.connectSlotsByName(FastaSequencesInput)

    def retranslateUi(self, FastaSequencesInput):
        _translate = QtCore.QCoreApplication.translate
        FastaSequencesInput.setWindowTitle(_translate("FastaSequencesInput", "Dialog"))
        self.label.setText(_translate("FastaSequencesInput", "Sequences (FASTA)"))
