# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/support/msa/visual/MsaViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MsaViewer(object):
    def setupUi(self, MsaViewer):
        MsaViewer.setObjectName("MsaViewer")
        MsaViewer.resize(633, 344)
        self.verticalLayout = QtWidgets.QVBoxLayout(MsaViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msaTable = QtWidgets.QTableView(MsaViewer)
        self.msaTable.setObjectName("msaTable")
        self.verticalLayout.addWidget(self.msaTable)

        self.retranslateUi(MsaViewer)
        QtCore.QMetaObject.connectSlotsByName(MsaViewer)

    def retranslateUi(self, MsaViewer):
        _translate = QtCore.QCoreApplication.translate
        MsaViewer.setWindowTitle(_translate("MsaViewer", "Form"))
