# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/support/msa/visual/MsaViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MsaViewer(object):
    def setupUi(self, MsaViewer):
        MsaViewer.setObjectName("MsaViewer")
        MsaViewer.resize(633, 344)
        self.gridLayout = QtWidgets.QGridLayout(MsaViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.maskCombo = QtWidgets.QComboBox(MsaViewer)
        self.maskCombo.setMinimumSize(QtCore.QSize(150, 0))
        self.maskCombo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.maskCombo.setObjectName("maskCombo")
        self.gridLayout.addWidget(self.maskCombo, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(MsaViewer)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.msaTable = QtWidgets.QTableView(MsaViewer)
        self.msaTable.setObjectName("msaTable")
        self.gridLayout.addWidget(self.msaTable, 1, 0, 1, 3)

        self.retranslateUi(MsaViewer)
        QtCore.QMetaObject.connectSlotsByName(MsaViewer)

    def retranslateUi(self, MsaViewer):
        _translate = QtCore.QCoreApplication.translate
        MsaViewer.setWindowTitle(_translate("MsaViewer", "Form"))
        self.label.setText(_translate("MsaViewer", "Masked Positions"))
