# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SchemaInstanceWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SchemaInstanceWidget(object):
    def setupUi(self, SchemaInstanceWidget):
        SchemaInstanceWidget.setObjectName("SchemaInstanceWidget")
        SchemaInstanceWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(SchemaInstanceWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.schemaTools = QtWidgets.QTabWidget(SchemaInstanceWidget)
        self.schemaTools.setObjectName("schemaTools")
        self.verticalLayout.addWidget(self.schemaTools)

        self.retranslateUi(SchemaInstanceWidget)
        self.schemaTools.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(SchemaInstanceWidget)

    def retranslateUi(self, SchemaInstanceWidget):
        _translate = QtCore.QCoreApplication.translate
        SchemaInstanceWidget.setWindowTitle(_translate("SchemaInstanceWidget", "Form"))
