# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SchemaSelectorWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SchemaSelectorWidget(object):
    def setupUi(self, SchemaSelectorWidget):
        SchemaSelectorWidget.setObjectName("SchemaSelectorWidget")
        SchemaSelectorWidget.resize(915, 654)
        self.verticalLayout = QtWidgets.QVBoxLayout(SchemaSelectorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(SchemaSelectorWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.resultsList = QtWidgets.QListWidget(self.splitter)
        self.resultsList.setObjectName("resultsList")
        self.resultsViewer = QtWidgets.QTableWidget(self.splitter)
        self.resultsViewer.setColumnCount(4)
        self.resultsViewer.setObjectName("resultsViewer")
        self.resultsViewer.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultsViewer.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsViewer.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsViewer.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsViewer.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(SchemaSelectorWidget)
        QtCore.QMetaObject.connectSlotsByName(SchemaSelectorWidget)

    def retranslateUi(self, SchemaSelectorWidget):
        _translate = QtCore.QCoreApplication.translate
        SchemaSelectorWidget.setWindowTitle(_translate("SchemaSelectorWidget", "Form"))
        item = self.resultsViewer.horizontalHeaderItem(0)
        item.setText(_translate("SchemaSelectorWidget", "<E>"))
        item = self.resultsViewer.horizontalHeaderItem(1)
        item.setText(_translate("SchemaSelectorWidget", "<M>"))
        item = self.resultsViewer.horizontalHeaderItem(2)
        item.setText(_translate("SchemaSelectorWidget", "Positions (MSA)"))
        item = self.resultsViewer.horizontalHeaderItem(3)
        item.setText(_translate("SchemaSelectorWidget", "Positions (Structure)"))
