# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/schema/visual/SchemaEnergyViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SchemaEnergyViewer(object):
    def setupUi(self, SchemaEnergyViewer):
        SchemaEnergyViewer.setObjectName("SchemaEnergyViewer")
        SchemaEnergyViewer.resize(924, 636)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SchemaEnergyViewer.sizePolicy().hasHeightForWidth())
        SchemaEnergyViewer.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(SchemaEnergyViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(SchemaEnergyViewer)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.chimeraNamesTable = QtWidgets.QTableView(SchemaEnergyViewer)
        self.chimeraNamesTable.setObjectName("chimeraNamesTable")
        self.gridLayout.addWidget(self.chimeraNamesTable, 3, 1, 1, 2)
        self.openResultsFolder = QtWidgets.QPushButton(SchemaEnergyViewer)
        self.openResultsFolder.setObjectName("openResultsFolder")
        self.gridLayout.addWidget(self.openResultsFolder, 4, 2, 1, 1)
        self.contactsTable = QtWidgets.QTableWidget(SchemaEnergyViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactsTable.sizePolicy().hasHeightForWidth())
        self.contactsTable.setSizePolicy(sizePolicy)
        self.contactsTable.setObjectName("contactsTable")
        self.contactsTable.setColumnCount(0)
        self.contactsTable.setRowCount(0)
        self.gridLayout.addWidget(self.contactsTable, 2, 1, 1, 2)
        self.resultsTable = TableViewClipboard(SchemaEnergyViewer)
        self.resultsTable.setObjectName("resultsTable")
        self.gridLayout.addWidget(self.resultsTable, 2, 0, 2, 1)
        self.label_3 = QtWidgets.QLabel(SchemaEnergyViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(SchemaEnergyViewer)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)

        self.retranslateUi(SchemaEnergyViewer)
        QtCore.QMetaObject.connectSlotsByName(SchemaEnergyViewer)

    def retranslateUi(self, SchemaEnergyViewer):
        _translate = QtCore.QCoreApplication.translate
        SchemaEnergyViewer.setWindowTitle(_translate("SchemaEnergyViewer", "Form"))
        self.label_2.setText(_translate("SchemaEnergyViewer", "Results"))
        self.openResultsFolder.setText(_translate("SchemaEnergyViewer", "Open Results Folder"))
        self.label_3.setText(_translate("SchemaEnergyViewer", "SCHEMA Energy Results"))
        self.label.setText(_translate("SchemaEnergyViewer", "Contacts"))
from ...core.Qt.visual.TableViewClipboard import TableViewClipboard
