# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/support/structure/MultiStructureSelector.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MultiStructureSelector(object):
    def setupUi(self, MultiStructureSelector):
        MultiStructureSelector.setObjectName("MultiStructureSelector")
        MultiStructureSelector.resize(578, 415)
        self.gridLayout = QtWidgets.QGridLayout(MultiStructureSelector)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(MultiStructureSelector)
        self.label.setStyleSheet("font-size: 24pt;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.infoLabel = QtWidgets.QLabel(MultiStructureSelector)
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.gridLayout.addWidget(self.infoLabel, 2, 0, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(MultiStructureSelector)
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout.addWidget(self.refreshButton, 2, 1, 1, 1)
        self.acceptButton = QtWidgets.QPushButton(MultiStructureSelector)
        self.acceptButton.setObjectName("acceptButton")
        self.gridLayout.addWidget(self.acceptButton, 2, 2, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(MultiStructureSelector)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 2, 3, 1, 1)
        self.structuresTable = QtWidgets.QTableView(MultiStructureSelector)
        self.structuresTable.setObjectName("structuresTable")
        self.gridLayout.addWidget(self.structuresTable, 1, 0, 1, 4)
        self.gridLayout.setColumnStretch(0, 1)

        self.retranslateUi(MultiStructureSelector)
        QtCore.QMetaObject.connectSlotsByName(MultiStructureSelector)

    def retranslateUi(self, MultiStructureSelector):
        _translate = QtCore.QCoreApplication.translate
        MultiStructureSelector.setWindowTitle(_translate("MultiStructureSelector", "Dialog"))
        self.label.setText(_translate("MultiStructureSelector", "Select Structures"))
        self.refreshButton.setText(_translate("MultiStructureSelector", "Refresh"))
        self.acceptButton.setText(_translate("MultiStructureSelector", "Accept"))
        self.cancelButton.setText(_translate("MultiStructureSelector", "Cancel"))
