# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/support/fasta/visual/FastaViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FastaViewer(object):
    def setupUi(self, FastaViewer):
        FastaViewer.setObjectName("FastaViewer")
        FastaViewer.resize(859, 541)
        self.gridLayout = QtWidgets.QGridLayout(FastaViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(FastaViewer)
        self.tabWidget.setObjectName("tabWidget")
        self.interactiveTab = QtWidgets.QWidget()
        self.interactiveTab.setObjectName("interactiveTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.interactiveTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sequencesTable = QtWidgets.QTableView(self.interactiveTab)
        self.sequencesTable.setObjectName("sequencesTable")
        self.gridLayout_2.addWidget(self.sequencesTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.interactiveTab, "")
        self.rawTab = QtWidgets.QWidget()
        self.rawTab.setObjectName("rawTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.rawTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sequencesTextEdit = QtWidgets.QTextEdit(self.rawTab)
        self.sequencesTextEdit.setReadOnly(True)
        self.sequencesTextEdit.setObjectName("sequencesTextEdit")
        self.gridLayout_3.addWidget(self.sequencesTextEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.rawTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(FastaViewer)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(FastaViewer)

    def retranslateUi(self, FastaViewer):
        _translate = QtCore.QCoreApplication.translate
        FastaViewer.setWindowTitle(_translate("FastaViewer", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.interactiveTab), _translate("FastaViewer", "Interactive"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rawTab), _translate("FastaViewer", "Raw"))
