# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/core/context/visual/RunQWidgetContext.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RunQWidgetContext(object):
    def setupUi(self, RunQWidgetContext):
        RunQWidgetContext.setObjectName("RunQWidgetContext")
        RunQWidgetContext.resize(749, 528)
        self.mainWindow = QtWidgets.QWidget(RunQWidgetContext)
        self.mainWindow.setObjectName("mainWindow")
        self.gridLayout = QtWidgets.QGridLayout(self.mainWindow)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.userManualLabel = QtWidgets.QLabel(self.mainWindow)
        self.userManualLabel.setTextFormat(QtCore.Qt.RichText)
        self.userManualLabel.setOpenExternalLinks(True)
        self.userManualLabel.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.userManualLabel.setObjectName("userManualLabel")
        self.gridLayout.addWidget(self.userManualLabel, 2, 2, 1, 1)
        self.centralWidget = QtWidgets.QWidget(self.mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout.addWidget(self.centralWidget, 0, 0, 2, 3)
        self.gridLayout.setRowStretch(0, 1)
        RunQWidgetContext.setCentralWidget(self.mainWindow)

        self.retranslateUi(RunQWidgetContext)
        QtCore.QMetaObject.connectSlotsByName(RunQWidgetContext)

    def retranslateUi(self, RunQWidgetContext):
        _translate = QtCore.QCoreApplication.translate
        RunQWidgetContext.setWindowTitle(_translate("RunQWidgetContext", "MainWindow"))
        self.userManualLabel.setText(_translate("RunQWidgetContext", "<html><head/><body><p><a href=\"https://github.com/TUM-CBR/pymol-plugins/wiki\"><span style=\" text-decoration: underline; color:#0000ff;\">User Manual</span></a></p></body></html>"))
