# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/core/executable/visual/KnownExecutable.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KnownExecutable(object):
    def setupUi(self, KnownExecutable):
        KnownExecutable.setObjectName("KnownExecutable")
        KnownExecutable.resize(573, 329)
        self.gridLayout = QtWidgets.QGridLayout(KnownExecutable)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.downloadButton = QtWidgets.QPushButton(KnownExecutable)
        self.downloadButton.setObjectName("downloadButton")
        self.gridLayout.addWidget(self.downloadButton, 3, 2, 1, 1)
        self.infoTextEdit = QtWidgets.QTextEdit(KnownExecutable)
        self.infoTextEdit.setReadOnly(True)
        self.infoTextEdit.setObjectName("infoTextEdit")
        self.gridLayout.addWidget(self.infoTextEdit, 1, 0, 1, 3)
        self.progressBar = QtWidgets.QProgressBar(KnownExecutable)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(KnownExecutable)
        self.label.setStyleSheet("font-size: 26px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(KnownExecutable)
        QtCore.QMetaObject.connectSlotsByName(KnownExecutable)

    def retranslateUi(self, KnownExecutable):
        _translate = QtCore.QCoreApplication.translate
        KnownExecutable.setWindowTitle(_translate("KnownExecutable", "Dialog"))
        self.downloadButton.setText(_translate("KnownExecutable", "Download"))
        self.label.setText(_translate("KnownExecutable", "Component Needed"))
