# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/chimeras/visual/ChimerasResults.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChimerasResults(object):
    def setupUi(self, ChimerasResults):
        ChimerasResults.setObjectName("ChimerasResults")
        ChimerasResults.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChimerasResults)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ChimerasResults)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(ChimerasResults)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.displayCombo = QtWidgets.QComboBox(ChimerasResults)
        self.displayCombo.setMinimumSize(QtCore.QSize(130, 0))
        self.displayCombo.setObjectName("displayCombo")
        self.horizontalLayout.addWidget(self.displayCombo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.resultsTable = QtWidgets.QTableWidget(ChimerasResults)
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(2)
        self.resultsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.resultsTable)

        self.retranslateUi(ChimerasResults)
        QtCore.QMetaObject.connectSlotsByName(ChimerasResults)

    def retranslateUi(self, ChimerasResults):
        _translate = QtCore.QCoreApplication.translate
        ChimerasResults.setWindowTitle(_translate("ChimerasResults", "Form"))
        self.label.setText(_translate("ChimerasResults", "<html><head/><body><p><span style=\" font-weight:700;\">Generated Chimeras</span></p></body></html>"))
        self.label_2.setText(_translate("ChimerasResults", "Display"))
        item = self.resultsTable.horizontalHeaderItem(0)
        item.setText(_translate("ChimerasResults", "Chimera"))
        item = self.resultsTable.horizontalHeaderItem(1)
        item.setText(_translate("ChimerasResults", "Sequence"))
