# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/chimeras/visual/ChimeraFragment.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChimeraFragment(object):
    def setupUi(self, ChimeraFragment):
        ChimeraFragment.setObjectName("ChimeraFragment")
        ChimeraFragment.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChimeraFragment)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pasteButton = QtWidgets.QPushButton(ChimeraFragment)
        self.pasteButton.setObjectName("pasteButton")
        self.horizontalLayout.addWidget(self.pasteButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.fragmentTable = QtWidgets.QTableWidget(ChimeraFragment)
        self.fragmentTable.setObjectName("fragmentTable")
        self.fragmentTable.setColumnCount(1)
        self.fragmentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fragmentTable.setHorizontalHeaderItem(0, item)
        self.verticalLayout.addWidget(self.fragmentTable)

        self.retranslateUi(ChimeraFragment)
        QtCore.QMetaObject.connectSlotsByName(ChimeraFragment)

    def retranslateUi(self, ChimeraFragment):
        _translate = QtCore.QCoreApplication.translate
        ChimeraFragment.setWindowTitle(_translate("ChimeraFragment", "Form"))
        self.pasteButton.setText(_translate("ChimeraFragment", "Paste"))
        item = self.fragmentTable.horizontalHeaderItem(0)
        item.setText(_translate("ChimeraFragment", "Sequence"))
