# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/chimeras/visual/ChimerasGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChimerasGenerator(object):
    def setupUi(self, ChimerasGenerator):
        ChimerasGenerator.setObjectName("ChimerasGenerator")
        ChimerasGenerator.resize(908, 698)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ChimerasGenerator)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(ChimerasGenerator)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fragmentsList = QtWidgets.QListWidget(ChimerasGenerator)
        self.fragmentsList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fragmentsList.setObjectName("fragmentsList")
        self.horizontalLayout.addWidget(self.fragmentsList)
        self.fragmentsStack = QtWidgets.QStackedWidget(ChimerasGenerator)
        self.fragmentsStack.setObjectName("fragmentsStack")
        self.horizontalLayout.addWidget(self.fragmentsStack)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(ChimerasGenerator)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.overhangsTable = QtWidgets.QTableWidget(ChimerasGenerator)
        self.overhangsTable.setObjectName("overhangsTable")
        self.overhangsTable.setColumnCount(1)
        self.overhangsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.overhangsTable.setHorizontalHeaderItem(0, item)
        self.verticalLayout.addWidget(self.overhangsTable)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(ChimerasGenerator)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.overhangLenght = QtWidgets.QLineEdit(ChimerasGenerator)
        self.overhangLenght.setMaximumSize(QtCore.QSize(50, 16777215))
        self.overhangLenght.setObjectName("overhangLenght")
        self.horizontalLayout_2.addWidget(self.overhangLenght)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.generateButton = QtWidgets.QPushButton(ChimerasGenerator)
        self.generateButton.setObjectName("generateButton")
        self.horizontalLayout_2.addWidget(self.generateButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ChimerasGenerator)
        QtCore.QMetaObject.connectSlotsByName(ChimerasGenerator)

    def retranslateUi(self, ChimerasGenerator):
        _translate = QtCore.QCoreApplication.translate
        ChimerasGenerator.setWindowTitle(_translate("ChimerasGenerator", "Form"))
        self.label_2.setText(_translate("ChimerasGenerator", "Fragments"))
        self.label_3.setText(_translate("ChimerasGenerator", "<html><head/><body><p><span style=\" font-weight:700;\">Enzyme Binding Site Codons</span></p></body></html>"))
        item = self.overhangsTable.horizontalHeaderItem(0)
        item.setText(_translate("ChimerasGenerator", "Codon"))
        self.label.setText(_translate("ChimerasGenerator", "<html><head/><body><p><span style=\" font-weight:700;\">Overhang Length</span></p></body></html>"))
        self.generateButton.setText(_translate("ChimerasGenerator", "Generate"))
