# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/coevolution/visual/CoevolutionViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoevolutionViewer(object):
    def setupUi(self, CoevolutionViewer):
        CoevolutionViewer.setObjectName("CoevolutionViewer")
        CoevolutionViewer.resize(645, 538)
        self.verticalLayout = QtWidgets.QVBoxLayout(CoevolutionViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(CoevolutionViewer)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.structureCombo = QtWidgets.QComboBox(self.widget)
        self.structureCombo.setObjectName("structureCombo")
        self.gridLayout.addWidget(self.structureCombo, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("font-weight: bold;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 2)
        self.exportResultsButton = QtWidgets.QPushButton(self.widget)
        self.exportResultsButton.setObjectName("exportResultsButton")
        self.gridLayout.addWidget(self.exportResultsButton, 1, 0, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(self.widget)
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout.addWidget(self.refreshButton, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.selectionErrorLabel = QtWidgets.QLabel(self.widget)
        self.selectionErrorLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.selectionErrorLabel.setText("")
        self.selectionErrorLabel.setObjectName("selectionErrorLabel")
        self.gridLayout.addWidget(self.selectionErrorLabel, 1, 4, 1, 1)
        self.sequenceCombo = QtWidgets.QComboBox(self.widget)
        self.sequenceCombo.setObjectName("sequenceCombo")
        self.gridLayout.addWidget(self.sequenceCombo, 2, 2, 1, 3)
        self.horizontalLayout.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(CoevolutionViewer)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(CoevolutionViewer)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(CoevolutionViewer)

    def retranslateUi(self, CoevolutionViewer):
        _translate = QtCore.QCoreApplication.translate
        CoevolutionViewer.setWindowTitle(_translate("CoevolutionViewer", "Form"))
        self.label_2.setText(_translate("CoevolutionViewer", "structure sequence"))
        self.label.setText(_translate("CoevolutionViewer", "structure"))
        self.label_3.setText(_translate("CoevolutionViewer", "Select visualization structure"))
        self.exportResultsButton.setText(_translate("CoevolutionViewer", "Save Result"))
        self.refreshButton.setText(_translate("CoevolutionViewer", "Refresh"))
        self.label_4.setText(_translate("CoevolutionViewer", "Saving"))
