# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/coevolution/visual/CoevolutionRunner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoevolutionRunner(object):
    def setupUi(self, CoevolutionRunner):
        CoevolutionRunner.setObjectName("CoevolutionRunner")
        CoevolutionRunner.resize(586, 341)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(CoevolutionRunner)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(CoevolutionRunner)
        self.label.setStyleSheet("font: 20pt \"Sans Serif\";\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.selectMsaWidget = QtWidgets.QWidget(CoevolutionRunner)
        self.selectMsaWidget.setStyleSheet("#selectMsaWidget {\n"
"\n"
"    border: 2px solid black;\n"
"}")
        self.selectMsaWidget.setObjectName("selectMsaWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.selectMsaWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.selectMsaWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectFileButton = QtWidgets.QPushButton(self.selectMsaWidget)
        self.selectFileButton.setObjectName("selectFileButton")
        self.horizontalLayout.addWidget(self.selectFileButton)
        self.selectedFileLabel = QtWidgets.QLabel(self.selectMsaWidget)
        self.selectedFileLabel.setText("")
        self.selectedFileLabel.setObjectName("selectedFileLabel")
        self.horizontalLayout.addWidget(self.selectedFileLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.selectMsaWidget)
        self.runWidget = QtWidgets.QWidget(CoevolutionRunner)
        self.runWidget.setStyleSheet("#runWidget {\n"
"    border: 2px solid black;\n"
"}")
        self.runWidget.setObjectName("runWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.runWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.runWidget)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.openButton = QtWidgets.QPushButton(self.runWidget)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout_2.addWidget(self.openButton)
        self.runCoevolutionButton = QtWidgets.QPushButton(self.runWidget)
        self.runCoevolutionButton.setObjectName("runCoevolutionButton")
        self.horizontalLayout_2.addWidget(self.runCoevolutionButton)
        self.coevolutionProgress = QtWidgets.QProgressBar(self.runWidget)
        self.coevolutionProgress.setProperty("value", 24)
        self.coevolutionProgress.setObjectName("coevolutionProgress")
        self.horizontalLayout_2.addWidget(self.coevolutionProgress)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.runWidget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 91, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)

        self.retranslateUi(CoevolutionRunner)
        QtCore.QMetaObject.connectSlotsByName(CoevolutionRunner)

    def retranslateUi(self, CoevolutionRunner):
        _translate = QtCore.QCoreApplication.translate
        CoevolutionRunner.setWindowTitle(_translate("CoevolutionRunner", "Widget"))
        self.label.setText(_translate("CoevolutionRunner", "Coevolution Analysis"))
        self.label_2.setText(_translate("CoevolutionRunner", "1. Select the MSA file"))
        self.selectFileButton.setText(_translate("CoevolutionRunner", "Select MSA File"))
        self.label_3.setText(_translate("CoevolutionRunner", "2. Select the Coevlution Analysis"))
        self.openButton.setText(_translate("CoevolutionRunner", "Open Existing"))
        self.runCoevolutionButton.setText(_translate("CoevolutionRunner", "Run New"))
