# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/coevolution/visual/CoevolutionByPairs.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoevolutionByPairs(object):
    def setupUi(self, CoevolutionByPairs):
        CoevolutionByPairs.setObjectName("CoevolutionByPairs")
        CoevolutionByPairs.resize(731, 665)
        self.verticalLayout = QtWidgets.QVBoxLayout(CoevolutionByPairs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(CoevolutionByPairs)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.distanceMin = QtWidgets.QLineEdit(self.widget)
        self.distanceMin.setObjectName("distanceMin")
        self.gridLayout.addWidget(self.distanceMin, 0, 5, 1, 1)
        self.distanceMax = QtWidgets.QLineEdit(self.widget)
        self.distanceMax.setObjectName("distanceMax")
        self.gridLayout.addWidget(self.distanceMax, 0, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("font-weight: bold;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.filterButton = QtWidgets.QPushButton(self.widget)
        self.filterButton.setMinimumSize(QtCore.QSize(0, 0))
        self.filterButton.setObjectName("filterButton")
        self.gridLayout.addWidget(self.filterButton, 0, 10, 1, 1)
        self.confidenceMin = QtWidgets.QLineEdit(self.widget)
        self.confidenceMin.setObjectName("confidenceMin")
        self.gridLayout.addWidget(self.confidenceMin, 0, 1, 1, 1)
        self.confidenceMax = QtWidgets.QLineEdit(self.widget)
        self.confidenceMax.setObjectName("confidenceMax")
        self.gridLayout.addWidget(self.confidenceMax, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.resultsTable = QtWidgets.QTableWidget(CoevolutionByPairs)
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(0)
        self.resultsTable.setRowCount(0)
        self.verticalLayout.addWidget(self.resultsTable)
        self.detailsTable = QtWidgets.QTableWidget(CoevolutionByPairs)
        self.detailsTable.setObjectName("detailsTable")
        self.detailsTable.setColumnCount(0)
        self.detailsTable.setRowCount(0)
        self.verticalLayout.addWidget(self.detailsTable)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 2)

        self.retranslateUi(CoevolutionByPairs)
        QtCore.QMetaObject.connectSlotsByName(CoevolutionByPairs)

    def retranslateUi(self, CoevolutionByPairs):
        _translate = QtCore.QCoreApplication.translate
        CoevolutionByPairs.setWindowTitle(_translate("CoevolutionByPairs", "Form"))
        self.label_3.setText(_translate("CoevolutionByPairs", "Distance:"))
        self.filterButton.setText(_translate("CoevolutionByPairs", "Filter"))
        self.label_2.setText(_translate("CoevolutionByPairs", "to"))
        self.label.setText(_translate("CoevolutionByPairs", "Confidence:"))
        self.label_4.setText(_translate("CoevolutionByPairs", "to"))
