# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/coevolution/visual/CoevolutionByPairs.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoevolutionByPairs(object):
    def setupUi(self, CoevolutionByPairs):
        CoevolutionByPairs.setObjectName("CoevolutionByPairs")
        CoevolutionByPairs.resize(549, 395)
        self.verticalLayout = QtWidgets.QVBoxLayout(CoevolutionByPairs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resultsTable = QtWidgets.QTableWidget(CoevolutionByPairs)
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(0)
        self.resultsTable.setRowCount(0)
        self.verticalLayout.addWidget(self.resultsTable)

        self.retranslateUi(CoevolutionByPairs)
        QtCore.QMetaObject.connectSlotsByName(CoevolutionByPairs)

    def retranslateUi(self, CoevolutionByPairs):
        _translate = QtCore.QCoreApplication.translate
        CoevolutionByPairs.setWindowTitle(_translate("CoevolutionByPairs", "Form"))
