# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/coevolution/visual/CoevolutionRunner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoevolutionRunner(object):
    def setupUi(self, CoevolutionRunner):
        CoevolutionRunner.setObjectName("CoevolutionRunner")
        CoevolutionRunner.resize(316, 213)
        self.verticalLayout = QtWidgets.QVBoxLayout(CoevolutionRunner)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(CoevolutionRunner)
        self.label.setStyleSheet("font: 20pt \"Sans Serif\";\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectFileButton = QtWidgets.QPushButton(CoevolutionRunner)
        self.selectFileButton.setObjectName("selectFileButton")
        self.horizontalLayout.addWidget(self.selectFileButton)
        self.selectedFileLabel = QtWidgets.QLabel(CoevolutionRunner)
        self.selectedFileLabel.setText("")
        self.selectedFileLabel.setObjectName("selectedFileLabel")
        self.horizontalLayout.addWidget(self.selectedFileLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.coevolutionProgress = QtWidgets.QProgressBar(CoevolutionRunner)
        self.coevolutionProgress.setProperty("value", 24)
        self.coevolutionProgress.setObjectName("coevolutionProgress")
        self.horizontalLayout_2.addWidget(self.coevolutionProgress)
        self.runCoevolutionButton = QtWidgets.QPushButton(CoevolutionRunner)
        self.runCoevolutionButton.setObjectName("runCoevolutionButton")
        self.horizontalLayout_2.addWidget(self.runCoevolutionButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 91, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(CoevolutionRunner)
        QtCore.QMetaObject.connectSlotsByName(CoevolutionRunner)

    def retranslateUi(self, CoevolutionRunner):
        _translate = QtCore.QCoreApplication.translate
        CoevolutionRunner.setWindowTitle(_translate("CoevolutionRunner", "Widget"))
        self.label.setText(_translate("CoevolutionRunner", "Coevolution Analysis"))
        self.selectFileButton.setText(_translate("CoevolutionRunner", "Select MSA File"))
        self.runCoevolutionButton.setText(_translate("CoevolutionRunner", "Run"))
