# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/dssp/visual/dssp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dssp(object):
    def setupUi(self, Dssp):
        Dssp.setObjectName("Dssp")
        Dssp.resize(482, 111)
        self.gridLayout = QtWidgets.QGridLayout(Dssp)
        self.gridLayout.setObjectName("gridLayout")
        self.structuresCombo = QtWidgets.QComboBox(Dssp)
        self.structuresCombo.setMinimumSize(QtCore.QSize(150, 0))
        self.structuresCombo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.structuresCombo.setObjectName("structuresCombo")
        self.gridLayout.addWidget(self.structuresCombo, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dssp)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 5, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(Dssp)
        self.refreshButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout.addWidget(self.refreshButton, 1, 2, 1, 1)
        self.runButton = QtWidgets.QPushButton(Dssp)
        self.runButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 4)
        self.label = QtWidgets.QLabel(Dssp)
        self.label.setStyleSheet("font-weight: bold;\n"
"font-size: 24px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 7)

        self.retranslateUi(Dssp)
        QtCore.QMetaObject.connectSlotsByName(Dssp)

    def retranslateUi(self, Dssp):
        _translate = QtCore.QCoreApplication.translate
        Dssp.setWindowTitle(_translate("Dssp", "Form"))
        self.label_2.setText(_translate("Dssp", "Select Structure"))
        self.refreshButton.setText(_translate("Dssp", "Refresh"))
        self.runButton.setText(_translate("Dssp", "Run"))
        self.label.setText(_translate("Dssp", "DSSP Secondary Structure Assignment"))
