# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/mpnn/visual/MpnnAdvancedOptions.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MpnnAdvancedOptions(object):
    def setupUi(self, MpnnAdvancedOptions):
        MpnnAdvancedOptions.setObjectName("MpnnAdvancedOptions")
        MpnnAdvancedOptions.resize(449, 426)
        self.gridLayout = QtWidgets.QGridLayout(MpnnAdvancedOptions)
        self.gridLayout.setObjectName("gridLayout")
        self.mpnnArgsTable = QtWidgets.QTableView(MpnnAdvancedOptions)
        self.mpnnArgsTable.setObjectName("mpnnArgsTable")
        self.gridLayout.addWidget(self.mpnnArgsTable, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(251, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.resetButton = QtWidgets.QPushButton(MpnnAdvancedOptions)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout.addWidget(self.resetButton, 2, 1, 1, 1)
        self.acceptButton = QtWidgets.QPushButton(MpnnAdvancedOptions)
        self.acceptButton.setObjectName("acceptButton")
        self.gridLayout.addWidget(self.acceptButton, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(MpnnAdvancedOptions)
        self.label.setStyleSheet("font-size: 26px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)

        self.retranslateUi(MpnnAdvancedOptions)
        QtCore.QMetaObject.connectSlotsByName(MpnnAdvancedOptions)

    def retranslateUi(self, MpnnAdvancedOptions):
        _translate = QtCore.QCoreApplication.translate
        MpnnAdvancedOptions.setWindowTitle(_translate("MpnnAdvancedOptions", "Dialog"))
        self.resetButton.setText(_translate("MpnnAdvancedOptions", "Reset Defaults"))
        self.acceptButton.setText(_translate("MpnnAdvancedOptions", "Accept"))
        self.label.setText(_translate("MpnnAdvancedOptions", "ProteinMPNN Advanced Options"))
