# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/mpnn/visual/MpnnViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MpnnViewer(object):
    def setupUi(self, MpnnViewer):
        MpnnViewer.setObjectName("MpnnViewer")
        MpnnViewer.resize(915, 505)
        self.gridLayout = QtWidgets.QGridLayout(MpnnViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.sequencesTextEdit = QtWidgets.QPlainTextEdit(MpnnViewer)
        self.sequencesTextEdit.setReadOnly(True)
        self.sequencesTextEdit.setObjectName("sequencesTextEdit")
        self.gridLayout.addWidget(self.sequencesTextEdit, 1, 0, 1, 3)
        self.textEdit = QtWidgets.QTextEdit(MpnnViewer)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 3, 0, 1, 3)
        self.resultsFolderButton = QtWidgets.QPushButton(MpnnViewer)
        self.resultsFolderButton.setObjectName("resultsFolderButton")
        self.gridLayout.addWidget(self.resultsFolderButton, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(MpnnViewer)
        self.label.setStyleSheet("font-size: 26px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.progressBar = QtWidgets.QProgressBar(MpnnViewer)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 4, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)

        self.retranslateUi(MpnnViewer)
        QtCore.QMetaObject.connectSlotsByName(MpnnViewer)

    def retranslateUi(self, MpnnViewer):
        _translate = QtCore.QCoreApplication.translate
        MpnnViewer.setWindowTitle(_translate("MpnnViewer", "Form"))
        self.textEdit.setHtml(_translate("MpnnViewer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">These sequences were produced using &quot;Protein MPNN&quot;. Learn more about it at: <a href=\"https://github.com/dauparas/ProteinMPNN\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/dauparas/ProteinMPNN.</span></a> If these sequences are used in an academic publication, please acknolwedge the usage of &quot;Protein MPNN&quot; with the citation below:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">@article{dauparas2022robust,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">  title={Robust deep learning--based protein sequence design using ProteinMPNN},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">  author={Dauparas, Justas and Anishchenko, Ivan and Bennett, Nathaniel and Bai, Hua and Ragotte, Robert J and Milles, Lukas F and Wicky, Basile IM and Courbet, Alexis and de Haas, Rob J and Bethel, Neville and others},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">  journal={Science},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">  volume={378},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">  number={6615},  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">  pages={49--56},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">  year={2022},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">  publisher={American Association for the Advancement of Science}</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">}</span></p></body></html>"))
        self.resultsFolderButton.setText(_translate("MpnnViewer", "Open Results Folder"))
        self.label.setText(_translate("MpnnViewer", "Protein MPNN Results"))
