# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/mpnn/visual/MpnnRunner.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MpnnRunner(object):
    def setupUi(self, MpnnRunner):
        MpnnRunner.setObjectName("MpnnRunner")
        MpnnRunner.resize(771, 584)
        self.gridLayout = QtWidgets.QGridLayout(MpnnRunner)
        self.gridLayout.setObjectName("gridLayout")
        self.tiedPositionsTable = QtWidgets.QTableView(MpnnRunner)
        self.tiedPositionsTable.setObjectName("tiedPositionsTable")
        self.gridLayout.addWidget(self.tiedPositionsTable, 3, 7, 1, 3)
        self.label_2 = QtWidgets.QLabel(MpnnRunner)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(MpnnRunner)
        self.label.setStyleSheet("font-size: 26px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 7)
        self.advancedOptionsButton = QtWidgets.QPushButton(MpnnRunner)
        self.advancedOptionsButton.setObjectName("advancedOptionsButton")
        self.gridLayout.addWidget(self.advancedOptionsButton, 5, 8, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(MpnnRunner)
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout.addWidget(self.refreshButton, 5, 7, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(MpnnRunner)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 0, 1, 10)
        self.label_3 = QtWidgets.QLabel(MpnnRunner)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 7, 1, 1)
        self.modelComboBox = QtWidgets.QComboBox(MpnnRunner)
        self.modelComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.modelComboBox.setObjectName("modelComboBox")
        self.gridLayout.addWidget(self.modelComboBox, 5, 2, 1, 1)
        self.runButton = QtWidgets.QPushButton(MpnnRunner)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 5, 9, 1, 1)
        self.numSequencesSpinBox = QtWidgets.QSpinBox(MpnnRunner)
        self.numSequencesSpinBox.setMinimum(1)
        self.numSequencesSpinBox.setMaximum(9999)
        self.numSequencesSpinBox.setProperty("value", 5)
        self.numSequencesSpinBox.setObjectName("numSequencesSpinBox")
        self.gridLayout.addWidget(self.numSequencesSpinBox, 5, 4, 1, 1)
        self.selectionsTable = QtWidgets.QTableView(MpnnRunner)
        self.selectionsTable.setObjectName("selectionsTable")
        self.gridLayout.addWidget(self.selectionsTable, 2, 0, 2, 7)
        self.label_4 = QtWidgets.QLabel(MpnnRunner)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(3, 3)

        self.retranslateUi(MpnnRunner)
        QtCore.QMetaObject.connectSlotsByName(MpnnRunner)

    def retranslateUi(self, MpnnRunner):
        _translate = QtCore.QCoreApplication.translate
        MpnnRunner.setWindowTitle(_translate("MpnnRunner", "Form"))
        self.label_2.setText(_translate("MpnnRunner", "Sequences to Generate"))
        self.label.setText(_translate("MpnnRunner", "ProteinMPNN Runner"))
        self.advancedOptionsButton.setText(_translate("MpnnRunner", "Advanced Options"))
        self.refreshButton.setText(_translate("MpnnRunner", "Refresh"))
        self.plainTextEdit.setPlainText(_translate("MpnnRunner", "Instructions:\n"
"\n"
"Select the pymol selections you wish to include/exclude for designing. Afterwards hit the \"run\" button. Use the \"refresh\" to re-populate the list of selections."))
        self.label_3.setText(_translate("MpnnRunner", "Tied Chains"))
        self.runButton.setText(_translate("MpnnRunner", "Run"))
        self.label_4.setText(_translate("MpnnRunner", "Model to use"))
