# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/cascades/visual/CascadesViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CascadesViewer(object):
    def setupUi(self, CascadesViewer):
        CascadesViewer.setObjectName("CascadesViewer")
        CascadesViewer.resize(701, 561)
        self.gridLayout = QtWidgets.QGridLayout(CascadesViewer)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.organismsTable = QtWidgets.QTableView(CascadesViewer)
        self.organismsTable.setObjectName("organismsTable")
        self.gridLayout.addWidget(self.organismsTable, 1, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(CascadesViewer)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.queryButton = QtWidgets.QPushButton(CascadesViewer)
        self.queryButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.queryButton.setObjectName("queryButton")
        self.gridLayout.addWidget(self.queryButton, 3, 2, 1, 2)
        self.label = QtWidgets.QLabel(CascadesViewer)
        self.label.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.equivalenceLineEdit = QtWidgets.QLineEdit(CascadesViewer)
        self.equivalenceLineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.equivalenceLineEdit.setObjectName("equivalenceLineEdit")
        self.gridLayout.addWidget(self.equivalenceLineEdit, 2, 3, 1, 1)
        self.queryProgressBar = QtWidgets.QProgressBar(CascadesViewer)
        self.queryProgressBar.setProperty("value", 24)
        self.queryProgressBar.setObjectName("queryProgressBar")
        self.gridLayout.addWidget(self.queryProgressBar, 4, 0, 1, 2)
        self.saveResultsButton = QtWidgets.QPushButton(CascadesViewer)
        self.saveResultsButton.setObjectName("saveResultsButton")
        self.gridLayout.addWidget(self.saveResultsButton, 4, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(CascadesViewer)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)

        self.retranslateUi(CascadesViewer)
        QtCore.QMetaObject.connectSlotsByName(CascadesViewer)

    def retranslateUi(self, CascadesViewer):
        _translate = QtCore.QCoreApplication.translate
        CascadesViewer.setWindowTitle(_translate("CascadesViewer", "Form"))
        self.label_2.setText(_translate("CascadesViewer", "Equivalence above"))
        self.queryButton.setText(_translate("CascadesViewer", "Query"))
        self.label.setText(_translate("CascadesViewer", "Cascade Organisms Viewer"))
        self.saveResultsButton.setText(_translate("CascadesViewer", "Save Results"))
        self.label_3.setText(_translate("CascadesViewer", "BLASTING away, but there is a lot to blast so it will take a few hours."))
