# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/cascades/visual/CascadesViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CascadesViewer(object):
    def setupUi(self, CascadesViewer):
        CascadesViewer.setObjectName("CascadesViewer")
        CascadesViewer.resize(1283, 864)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CascadesViewer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(CascadesViewer)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.organismsTable = QtWidgets.QTableView(self.layoutWidget)
        self.organismsTable.setObjectName("organismsTable")
        self.verticalLayout.addWidget(self.organismsTable)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.saveResultsButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.saveResultsButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.saveResultsButton.setObjectName("saveResultsButton")
        self.gridLayout.addWidget(self.saveResultsButton, 1, 2, 1, 1)
        self.queryButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.queryButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.queryButton.setObjectName("queryButton")
        self.gridLayout.addWidget(self.queryButton, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.progressWidget = QtWidgets.QWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressWidget.sizePolicy().hasHeightForWidth())
        self.progressWidget.setSizePolicy(sizePolicy)
        self.progressWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.progressWidget.setObjectName("progressWidget")
        self.gridLayout.addWidget(self.progressWidget, 0, 1, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 3, 1)
        self.verticalLayout_2.addWidget(self.splitter)

        self.retranslateUi(CascadesViewer)
        QtCore.QMetaObject.connectSlotsByName(CascadesViewer)

    def retranslateUi(self, CascadesViewer):
        _translate = QtCore.QCoreApplication.translate
        CascadesViewer.setWindowTitle(_translate("CascadesViewer", "Form"))
        self.label.setText(_translate("CascadesViewer", "Cascade Organisms Viewer"))
        self.saveResultsButton.setText(_translate("CascadesViewer", "Save Results"))
        self.queryButton.setText(_translate("CascadesViewer", "Filter"))
