# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbr/cascades/visual/CascadesMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CascadesMain(object):
    def setupUi(self, CascadesMain):
        CascadesMain.setObjectName("CascadesMain")
        CascadesMain.resize(973, 639)
        self.gridLayout = QtWidgets.QGridLayout(CascadesMain)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(CascadesMain)
        self.label.setStyleSheet("font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 10)
        self.selectFastaButton = QtWidgets.QPushButton(CascadesMain)
        self.selectFastaButton.setObjectName("selectFastaButton")
        self.gridLayout.addWidget(self.selectFastaButton, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(CascadesMain)
        self.label_3.setStyleSheet("font-weight: bold;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 10)
        self.label_4 = QtWidgets.QLabel(CascadesMain)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(CascadesMain)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.selectFastaLabel = QtWidgets.QLabel(CascadesMain)
        self.selectFastaLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.selectFastaLabel.setText("")
        self.selectFastaLabel.setObjectName("selectFastaLabel")
        self.gridLayout.addWidget(self.selectFastaLabel, 4, 3, 1, 1)
        self.loadExistingButton = QtWidgets.QPushButton(CascadesMain)
        self.loadExistingButton.setObjectName("loadExistingButton")
        self.gridLayout.addWidget(self.loadExistingButton, 2, 0, 1, 1)
        self.emailLineEdit = QtWidgets.QLineEdit(CascadesMain)
        self.emailLineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.gridLayout.addWidget(self.emailLineEdit, 6, 7, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(CascadesMain)
        self.label_2.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 10)
        self.label_6 = QtWidgets.QLabel(CascadesMain)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 4, 1, 1)
        self.createButton = QtWidgets.QPushButton(CascadesMain)
        self.createButton.setObjectName("createButton")
        self.gridLayout.addWidget(self.createButton, 6, 9, 1, 1)
        self.createCascadeTable = QtWidgets.QTableView(CascadesMain)
        self.createCascadeTable.setObjectName("createCascadeTable")
        self.gridLayout.addWidget(self.createCascadeTable, 5, 0, 1, 10)
        self.identityTargetLineEdit = QtWidgets.QLineEdit(CascadesMain)
        self.identityTargetLineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.identityTargetLineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.identityTargetLineEdit.setObjectName("identityTargetLineEdit")
        self.gridLayout.addWidget(self.identityTargetLineEdit, 6, 5, 1, 1)

        self.retranslateUi(CascadesMain)
        QtCore.QMetaObject.connectSlotsByName(CascadesMain)

    def retranslateUi(self, CascadesMain):
        _translate = QtCore.QCoreApplication.translate
        CascadesMain.setWindowTitle(_translate("CascadesMain", "Form"))
        self.label.setText(_translate("CascadesMain", "Option 1: Load existing results"))
        self.selectFastaButton.setText(_translate("CascadesMain", "Select File"))
        self.label_3.setText(_translate("CascadesMain", "Option 2: Create new"))
        self.label_4.setText(_translate("CascadesMain", "email"))
        self.label_5.setText(_translate("CascadesMain", "Select Fasta File"))
        self.loadExistingButton.setText(_translate("CascadesMain", "Select File"))
        self.label_2.setText(_translate("CascadesMain", "Cascade BLAST"))
        self.label_6.setText(_translate("CascadesMain", "minimum identity target"))
        self.createButton.setText(_translate("CascadesMain", "Create"))
