---
name: "pre-release"

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

jobs:
  gh_pre_release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          lfs: true
          fetch-depth: 0
          submodules: true

      - name: "Setup Python for Building"
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pip' # caching pip dependencies

      - run: pip install -r .github/workflows/support/requirements.txt

      #- name: "Run pyright"
      #  run: pyright -p ./pyrightconfig.github.json --verbose

      - run: wget -O devops/tmp/clustalo-win64.zip http://www.clustal.org/omega/clustal-omega-1.2.2-win64.zip
      - run: unzip -d cbr/clustal/resources/ devops/tmp/clustalo-win64.zip
      - run: mv cbr/clustal/resources/clustal-*/* cbr/clustal/resources/

      # Download the additional executables
      - run: wget -O devops/tmp/resources.tar.gz https://github.com/TUM-CBR/resources/releases/download/20231204/resources.tar.gz
      - run: tar -xvf devops/tmp/resources.tar.gz -C devops/tmp/
    
      # Add the APBS executabels
      - run: mv devops/tmp/APBS.windows cbr/apbs/resources/
      - run: mv devops/tmp/pdb2pqr.windows cbr/apbs/resources/

      # Add the DSSP executable
      - run: mv devops/tmp/dssp.windows/* cbr/dssp/resources/

      # Add the cbrextra executable
      - run: wget -O devops/tmp/cbrextra.win64.zip https://github.com/TUM-CBR/cbr-tools-extra/releases/download/nightly-20240314/cbr-tools-extra-20240314-win64.zip
      - run: unzip -d cbr/extra/resources/ devops/tmp/cbrextra.win64.zip

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: "cbr-tools-${{ env.date }}-win64.zip"
          exclusions: '*.git* *.vscode* *.pyproject *.pyproject.user *devops/tmp/* **/*.gitkeep test_pymol.py'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_ACCESS_TOKEN }}"
          prerelease: true
          automatic_release_tag: "nightly-${{ env.date }}"
          title: "Nightly Build ${{ env.date }}"
          files: "cbr-tools-${{ env.date }}-win64.zip"
